# -*- coding: utf-8 -*-
#!/usr/bin/python3

import configparser
import os
import os.path
import pprint
import re
import csv
import codecs

class MsgInfo(object):
	def __init__(self,csvname,msgid,msgname,comment):
		self.csvname = csvname
		self.msgid = msgid
		self.msgname = msgname
		self.comment = comment
		
	csvname = ""
	msgid = ""
	msgname = ""
	comment = ""
class WrapFile:
	fs = None
	def __init__(self,real_file):
		self.fs = real_file
	def writelines(self,s):
		self.fs.write(s + "\n")
	def flush(self):
		self.fs.flush()
	def close(self):
		self.fs.close()

def ParseDefine(fs,msgidList):
	fs.writelines("// Generated By csv2cs Do not Edit");

	index = 1;

	for _msgDef in msgidList:
		if index == 1:
			fs.writelines("public enum " + _msgDef.csvname + "\n" "{" "\n" "\tNone = -1,");
			index = 2;

		fs.writelines("\t%s = %s, //%s"%( _msgDef.msgname, _msgDef.msgid,_msgDef.comment));

	fs.writelines("}");
	fs.flush();
	fs.close();

def ParseInitClassDefine(fs,msgidList):
	fs.writelines("// Generated By csv2cs Do not Edit");

	index = 1;

	for _msgDef in msgidList:
		if index == 1:
			fs.writelines("public class " + _msgDef.csvname + "\n" "{" "\n" "");
			index = 2;

		fs.writelines("\tpublic const int %s = %s; //%s"%( _msgDef.msgname, _msgDef.msgid,_msgDef.comment));

	fs.writelines("}");
	fs.flush();
	fs.close();

def GenDefine():
	begin_path = os.getcwd()
	config=configparser.ConfigParser()
	config.read("Config.ini")
	csvRootPath =  config.get("DataPath","dataPath")
	csRootPath = config.get("CSDataIDDefinePath","tableCSPath")
	csUIIDRootPath = config.get("CSDataIDDefinePath","tableUIIDCSPath")
	csEffectIDRootPath = config.get("CSDataIDDefinePath","tableEffectIDCSPath")
	csCommonIDRootPath = config.get("CSDataIDDefinePath","tableCommonIDCSPath")

	csvPath = csvRootPath + "ClientTables\\Hint.csv"
	csvname = "HintIDDefine"
	csPath = csRootPath + csvname + ".cs"
	contextList = LoadHintCSV(csvPath, csvname)
	WritecsClass(csvPath,csPath,contextList)
	
	csvPath = csvRootPath + "ClientTables\\UIData.csv"
	csvname = "UIID"
	csPath = csUIIDRootPath + csvname + ".cs"
	contextList = LoadUIIDCSV(csvPath, csvname)
	Writecs(csvPath,csPath,contextList)

	csvPath = csvRootPath + "ClientTables\\EffectConfig.csv"
	csvname = "EffectIDDefine"
	csPath = csEffectIDRootPath + csvname + ".cs"
	contextList = LoadEffectCSV(csvPath, csvname)
	WritecsClass(csvPath,csPath,contextList)

	csvPath = csvRootPath + "PublicTables\\GlobalVariables.csv"
	csvname = "GlobalVariableIDDefine"
	csPath = csCommonIDRootPath + csvname + ".cs"
	contextList = LoadGlobalvalueCSV(csvPath, csvname)
	WritecsClass(csvPath,csPath,contextList)

	csvPath = csvRootPath + "ClientTables\\AudioResource.csv"
	csvname = "AudioResourceIDDefine"
	csPath = csRootPath + csvname + ".cs"
	contextList = LoadAudioResourceCSV(csvPath, csvname)
	Writecs(csvPath,csPath,contextList)
	
	csvPath = csvRootPath + "ClientTables\\CommonComponent.csv"
	csvname = "UITipsIDDefine"
	csPath = csRootPath + csvname + ".cs"
	contextList = LoadCommonComponentCSV(csvPath, csvname)
	Writecs(csvPath,csPath,contextList)
	

def Writecs(csvPath,csPath,contextList):
	print("START GEN" + csPath)
	fs = WrapFile(open(csPath,"w+",-1,"utf-8"))
	ParseDefine(fs,contextList)
	print(csPath + " done")
	
def WritecsClass(csvPath,csPath,contextList):
	print("START GEN" + csPath)
	fs = WrapFile(open(csPath,"w+",-1,"utf-8"))
	ParseInitClassDefine(fs,contextList)
	print(csPath + " done")

def LoadHintCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			csvContextList.append(MsgInfo(csvname,row[0],row[1],row[4]))
	return csvContextList	
	
def LoadUIIDCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			textname = row[3] + "_" + row[0]
			csvContextList.append(MsgInfo(csvname,row[0], textname, row[3]))
	return csvContextList	

def LoadEffectCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			csvContextList.append(MsgInfo(csvname,row[0],row[1],row[9]))
	return csvContextList	

def LoadGlobalvalueCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			csvContextList.append(MsgInfo(csvname,row[0],row[2],row[5]))
	return csvContextList	

def LoadAudioResourceCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			if row[0] != row[1]:
				csvContextList.append(MsgInfo(csvname,row[0],row[1],row[8]))
	return csvContextList	

def LoadCommonComponentCSV(csvpath, csvname):
	csvContextList = []
	with open(csvpath) as csvfile:
		csvreader = csv.reader(csvfile)
		next(csvreader)
		next(csvreader)
		next(csvreader)
		next(csvreader)

		for row in csvreader:
			csvContextList.append(MsgInfo(csvname,row[0],row[1],row[2]))
	return csvContextList	

GenDefine()
