//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CharacterDataCommand.proto
// Note: requires additional types generated from: SkillCommand.proto
// Note: requires additional types generated from: ItemDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterBaseData")]
  public partial class CharacterBaseData : global::ProtoBuf.IExtensible
  {
    public CharacterBaseData() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _roleid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private uint _pos_x = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private uint _pos_y = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _atb = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"atb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> atb
    {
      get { return _atb; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _ext = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ext
    {
      get { return _ext; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.SkillInfo> _skill = new global::System.Collections.Generic.List<ProtoCmd.SkillInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.SkillInfo> skill
    {
      get { return _skill; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> _equipdata = new global::System.Collections.Generic.List<ProtoCmd.ItemSerialize>();
    [global::ProtoBuf.ProtoMember(9, Name=@"equipdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> equipdata
    {
      get { return _equipdata; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _final_atb = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"final_atb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> final_atb
    {
      get { return _final_atb; }
    }
  
    private uint _is_virtual = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_virtual", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_virtual
    {
      get { return _is_virtual; }
      set { _is_virtual = value; }
    }
    private uint _awaken = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"awaken", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint awaken
    {
      get { return _awaken; }
      set { _awaken = value; }
    }
    private uint _fight = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"fight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fight
    {
      get { return _fight; }
      set { _fight = value; }
    }
    private uint _breakthrough = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"breakthrough", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint breakthrough
    {
      get { return _breakthrough; }
      set { _breakthrough = value; }
    }
    private uint _usingcardface = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"usingcardface", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint usingcardface
    {
      get { return _usingcardface; }
      set { _usingcardface = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _activatecardface = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(16, Name=@"activatecardface", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> activatecardface
    {
      get { return _activatecardface; }
    }
  
    private uint _rand_index = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"rand_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rand_index
    {
      get { return _rand_index; }
      set { _rand_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterDataClientCmd")]
  public partial class CharacterDataClientCmd : global::ProtoBuf.IExtensible
  {
    public CharacterDataClientCmd() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.CharacterBaseData> _base_data = new global::System.Collections.Generic.List<ProtoCmd.CharacterBaseData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"base_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.CharacterBaseData> base_data
    {
      get { return _base_data; }
    }
  
    private bool _is_fb = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_fb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_fb
    {
      get { return _is_fb; }
      set { _is_fb = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharExtFlagData")]
  public partial class CharExtFlagData : global::ProtoBuf.IExtensible
  {
    public CharExtFlagData() {}
    
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendCharExtFlagCmd")]
  public partial class SendCharExtFlagCmd : global::ProtoBuf.IExtensible
  {
    public SendCharExtFlagCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.CharExtFlagData> _data = new global::System.Collections.Generic.List<ProtoCmd.CharExtFlagData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.CharExtFlagData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectAidCharCmd")]
  public partial class SelectAidCharCmd : global::ProtoBuf.IExtensible
  {
    public SelectAidCharCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _src_charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"src_charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_charid
    {
      get { return _src_charid; }
      set { _src_charid = value; }
    }
    private uint _dst_charid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dst_charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dst_charid
    {
      get { return _dst_charid; }
      set { _dst_charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcceptRankUpTaskClientCmd")]
  public partial class AcceptRankUpTaskClientCmd : global::ProtoBuf.IExtensible
  {
    public AcceptRankUpTaskClientCmd() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteRankUpClientCmd")]
  public partial class CompleteRankUpClientCmd : global::ProtoBuf.IExtensible
  {
    public CompleteRankUpClientCmd() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private bool _ret = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncBehavior")]
  public partial class SyncBehavior : global::ProtoBuf.IExtensible
  {
    public SyncBehavior() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.BehaviorInstruction> _behaviors = new global::System.Collections.Generic.List<ProtoCmd.BehaviorInstruction>();
    [global::ProtoBuf.ProtoMember(1, Name=@"behaviors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.BehaviorInstruction> behaviors
    {
      get { return _behaviors; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BehaviorInstruction")]
  public partial class BehaviorInstruction : global::ProtoBuf.IExtensible
  {
    public BehaviorInstruction() {}
    
    private uint _char_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _cur_time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cur_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_time
    {
      get { return _cur_time; }
      set { _cur_time = value; }
    }
    private float _cur_pos_x = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cur_pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_pos_x
    {
      get { return _cur_pos_x; }
      set { _cur_pos_x = value; }
    }
    private float _cur_pos_y = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cur_pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_pos_y
    {
      get { return _cur_pos_y; }
      set { _cur_pos_y = value; }
    }
    private float _cur_pos_z = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cur_pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_pos_z
    {
      get { return _cur_pos_z; }
      set { _cur_pos_z = value; }
    }
    private float _cur_rot_x = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cur_rot_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_rot_x
    {
      get { return _cur_rot_x; }
      set { _cur_rot_x = value; }
    }
    private float _cur_rot_y = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cur_rot_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_rot_y
    {
      get { return _cur_rot_y; }
      set { _cur_rot_y = value; }
    }
    private float _cur_rot_z = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cur_rot_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cur_rot_z
    {
      get { return _cur_rot_z; }
      set { _cur_rot_z = value; }
    }
    private uint _cur_room_id = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cur_room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_room_id
    {
      get { return _cur_room_id; }
      set { _cur_room_id = value; }
    }
    private uint _behavior_id = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"behavior_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint behavior_id
    {
      get { return _behavior_id; }
      set { _behavior_id = value; }
    }
    private float _behavior_index = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"behavior_index", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float behavior_index
    {
      get { return _behavior_index; }
      set { _behavior_index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CollisionClientCmd")]
  public partial class CollisionClientCmd : global::ProtoBuf.IExtensible
  {
    public CollisionClientCmd() {}
    
    private uint _src_roleid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_roleid
    {
      get { return _src_roleid; }
      set { _src_roleid = value; }
    }
    private uint _dest_roleid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dest_roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_roleid
    {
      get { return _dest_roleid; }
      set { _dest_roleid = value; }
    }
    private uint _linking = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"linking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint linking
    {
      get { return _linking; }
      set { _linking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshCharacterFormClientCmd")]
  public partial class RefreshCharacterFormClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshCharacterFormClientCmd() {}
    
    private uint _card_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _form_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"form_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> form_id
    {
      get { return _form_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRetireClientCmd")]
  public partial class ReqRetireClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqRetireClientCmd() {}
    
    private uint _card_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddCharExpClientCmd")]
  public partial class AddCharExpClientCmd : global::ProtoBuf.IExtensible
  {
    public AddCharExpClientCmd() {}
    
    private uint _card_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_id
    {
      get { return _card_id; }
      set { _card_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemNumPair> _info = new global::System.Collections.Generic.List<ProtoCmd.ItemNumPair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemNumPair> info
    {
      get { return _info; }
    }
  
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetAddExpTipClientCmd")]
  public partial class SetAddExpTipClientCmd : global::ProtoBuf.IExtensible
  {
    public SetAddExpTipClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GiveGiftClientCmd")]
  public partial class GiveGiftClientCmd : global::ProtoBuf.IExtensible
  {
    public GiveGiftClientCmd() {}
    
    private uint _role_id1 = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id1
    {
      get { return _role_id1; }
      set { _role_id1 = value; }
    }
    private uint _role_id2 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role_id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id2
    {
      get { return _role_id2; }
      set { _role_id2 = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspGiveGiftCmd")]
  public partial class RspGiveGiftCmd : global::ProtoBuf.IExtensible
  {
    public RspGiveGiftCmd() {}
    
    private uint _role_id1 = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id1
    {
      get { return _role_id1; }
      set { _role_id1 = value; }
    }
    private uint _role_id2 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role_id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id2
    {
      get { return _role_id2; }
      set { _role_id2 = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _add_link = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"add_link", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint add_link
    {
      get { return _add_link; }
      set { _add_link = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GiftInfo")]
  public partial class GiftInfo : global::ProtoBuf.IExtensible
  {
    public GiftInfo() {}
    
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _item_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> item_id
    {
      get { return _item_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshGiftInfoCmd")]
  public partial class RefreshGiftInfoCmd : global::ProtoBuf.IExtensible
  {
    public RefreshGiftInfoCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.GiftInfo> _data = new global::System.Collections.Generic.List<ProtoCmd.GiftInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.GiftInfo> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewCardInfoCmd")]
  public partial class NewCardInfoCmd : global::ProtoBuf.IExtensible
  {
    public NewCardInfoCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _card_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"card_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> card_id
    {
      get { return _card_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAwakenCmd")]
  public partial class ReqAwakenCmd : global::ProtoBuf.IExtensible
  {
    public ReqAwakenCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspAwakenCmd")]
  public partial class RspAwakenCmd : global::ProtoBuf.IExtensible
  {
    public RspAwakenCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAwakenAwardCmd")]
  public partial class ReqAwakenAwardCmd : global::ProtoBuf.IExtensible
  {
    public ReqAwakenAwardCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspAwakenAwardCmd")]
  public partial class RspAwakenAwardCmd : global::ProtoBuf.IExtensible
  {
    public RspAwakenAwardCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspUpdateOnlineTimeCmd")]
  public partial class RspUpdateOnlineTimeCmd : global::ProtoBuf.IExtensible
  {
    public RspUpdateOnlineTimeCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _onlinetime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"onlinetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint onlinetime
    {
      get { return _onlinetime; }
      set { _onlinetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardData")]
  public partial class CardData : global::ProtoBuf.IExtensible
  {
    public CardData() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _roleid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCardData")]
  public partial class CreateCardData : global::ProtoBuf.IExtensible
  {
    public CreateCardData() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.CardData> _data = new global::System.Collections.Generic.List<ProtoCmd.CardData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.CardData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSwapCardFaceCmd")]
  public partial class ReqSwapCardFaceCmd : global::ProtoBuf.IExtensible
  {
    public ReqSwapCardFaceCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _cardFaceid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardFaceid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardFaceid
    {
      get { return _cardFaceid; }
      set { _cardFaceid = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBreakthroughClientCmd")]
  public partial class ReqBreakthroughClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqBreakthroughClientCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _material_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"material_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint material_type
    {
      get { return _material_type; }
      set { _material_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBreakthroughClientCmd")]
  public partial class RspBreakthroughClientCmd : global::ProtoBuf.IExtensible
  {
    public RspBreakthroughClientCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _rst = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterAtb")]
    public enum CharacterAtb
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Level", Value=0)]
      Atb_Level = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Exp", Value=1)]
      Atb_Exp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Hp", Value=2)]
      Atb_Hp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Mp", Value=3)]
      Atb_Mp = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_MaxHp", Value=4)]
      Atb_MaxHp = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_MaxMp", Value=5)]
      Atb_MaxMp = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Ap", Value=6)]
      Atb_Ap = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_ApRate", Value=7)]
      Atb_ApRate = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Dp", Value=8)]
      Atb_Dp = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DpRate", Value=9)]
      Atb_DpRate = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_IgnoreDp", Value=10)]
      Atb_IgnoreDp = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Crit", Value=11)]
      Atb_Crit = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_CritDef", Value=12)]
      Atb_CritDef = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_CritDamage", Value=13)]
      Atb_CritDamage = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_CritDamageDef", Value=14)]
      Atb_CritDamageDef = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_EffectHit", Value=15)]
      Atb_EffectHit = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_EffectDef", Value=16)]
      Atb_EffectDef = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageAdd", Value=17)]
      Atb_DamageAdd = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageSub", Value=18)]
      Atb_DamageSub = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_ApSpeed", Value=19)]
      Atb_ApSpeed = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Speed", Value=20)]
      Atb_Speed = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_ApSpeedRate", Value=21)]
      Atb_ApSpeedRate = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_SpeedRate", Value=22)]
      Atb_SpeedRate = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_HpRecovery", Value=23)]
      Atb_HpRecovery = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_MpRecovery", Value=24)]
      Atb_MpRecovery = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_HpRate", Value=25)]
      Atb_HpRate = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_CoolDown", Value=26)]
      Atb_CoolDown = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Sex", Value=27)]
      Atb_Sex = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Mass", Value=28)]
      Atb_Mass = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Rarity", Value=30)]
      Atb_Rarity = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_CurrentHpRate", Value=33)]
      Atb_CurrentHpRate = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_HealAdd", Value=34)]
      Atb_HealAdd = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageMul", Value=35)]
      Atb_DamageMul = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DodgeRate", Value=36)]
      Atb_DodgeRate = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_TiredRate", Value=37)]
      Atb_TiredRate = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_BeCuredAdd", Value=44)]
      Atb_BeCuredAdd = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Max", Value=48)]
      Atb_Max = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageRebound", Value=201)]
      Atb_DamageRebound = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageSuck", Value=202)]
      Atb_DamageSuck = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_BuffImmunity", Value=203)]
      Atb_BuffImmunity = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageImmunity", Value=204)]
      Atb_DamageImmunity = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DamageShareWeak", Value=205)]
      Atb_DamageShareWeak = 205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_AttrSwap", Value=206)]
      Atb_AttrSwap = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Shield", Value=207)]
      Atb_Shield = 207,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_RecovryMpSoon", Value=301)]
      Atb_RecovryMpSoon = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_RecovryMp", Value=302)]
      Atb_RecovryMp = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_RecovryHp", Value=305)]
      Atb_RecovryHp = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Slow", Value=115)]
      Atb_Slow = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Skill", Value=116)]
      Atb_Skill = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Frost", Value=119)]
      Atb_Frost = 119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_DieSoon", Value=310)]
      Atb_DieSoon = 310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_Suspend", Value=311)]
      Atb_Suspend = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_NoSelect", Value=312)]
      Atb_NoSelect = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_NoDamage", Value=313)]
      Atb_NoDamage = 313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Atb_SettleExpAdd", Value=400)]
      Atb_SettleExpAdd = 400
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CharacterExt")]
    public enum CharacterExt
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Energy", Value=0)]
      Ext_Energy = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_AidChar", Value=1)]
      Ext_AidChar = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Cultivate", Value=2)]
      Ext_Cultivate = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_RankUp", Value=3)]
      Ext_RankUp = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Rank", Value=4)]
      Ext_Rank = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Travel", Value=5)]
      Ext_Travel = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Form", Value=6)]
      Ext_Form = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Fatigue", Value=7)]
      Ext_Fatigue = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_FatigueTime", Value=8)]
      Ext_FatigueTime = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_PrepareTeam", Value=9)]
      Ext_PrepareTeam = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Breakthrough", Value=10)]
      Ext_Breakthrough = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ext_Max", Value=11)]
      Ext_Max = 11
    }
  
}