//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatCommand.proto
// Note: requires additional types generated from: ErrorCode.proto
// Note: requires additional types generated from: ItemDefine.proto
// Note: requires additional types generated from: PlayerDataDefine.proto
// Note: requires additional types generated from: ActivityDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatDestPlayerInfo")]
  public partial class ChatDestPlayerInfo : global::ProtoBuf.IExtensible
  {
    public ChatDestPlayerInfo() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _facepic = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"facepic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint facepic
    {
      get { return _facepic; }
      set { _facepic = value; }
    }
    private string _signiture = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"signiture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string signiture
    {
      get { return _signiture; }
      set { _signiture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMCmdData")]
  public partial class GMCmdData : global::ProtoBuf.IExtensible
  {
    public GMCmdData() {}
    
    private string _command = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string command
    {
      get { return _command; }
      set { _command = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMChatClientCmd")]
  public partial class GMChatClientCmd : global::ProtoBuf.IExtensible
  {
    public GMChatClientCmd() {}
    
    private ProtoCmd.GMCmdData _cmd_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cmd_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.GMCmdData cmd_data
    {
      get { return _cmd_data; }
      set { _cmd_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatTextClientCmd")]
  public partial class ChatTextClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatTextClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatReturnTextClientCmd")]
  public partial class ChatReturnTextClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatReturnTextClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonChatClientCmd")]
  public partial class CommonChatClientCmd : global::ProtoBuf.IExtensible
  {
    public CommonChatClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _playername = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playername
    {
      get { return _playername; }
      set { _playername = value; }
    }
    private uint _headindex = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headindex
    {
      get { return _headindex; }
      set { _headindex = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private uint _headback = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"headback", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headback
    {
      get { return _headback; }
      set { _headback = value; }
    }
    private uint _cur_time = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cur_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_time
    {
      get { return _cur_time; }
      set { _cur_time = value; }
    }
    private uint _channel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatOpenPrivateWndClientCmd")]
  public partial class ChatOpenPrivateWndClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatOpenPrivateWndClientCmd() {}
    
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private ProtoCmd.ChatDestPlayerInfo _playerinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.ChatDestPlayerInfo playerinfo
    {
      get { return _playerinfo; }
      set { _playerinfo = value; }
    }
    private uint _errCode = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatPrivateClientCmd")]
  public partial class ChatPrivateClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatPrivateClientCmd() {}
    
    private string _srcPlayername = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"srcPlayername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string srcPlayername
    {
      get { return _srcPlayername; }
      set { _srcPlayername = value; }
    }
    private string _destPlayerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"destPlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string destPlayerName
    {
      get { return _destPlayerName; }
      set { _destPlayerName = value; }
    }
    private uint _headindex = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headindex
    {
      get { return _headindex; }
      set { _headindex = value; }
    }
    private uint _src_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"src_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_level
    {
      get { return _src_level; }
      set { _src_level = value; }
    }
    private uint _src_vip = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"src_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_vip
    {
      get { return _src_vip; }
      set { _src_vip = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private uint _errCode = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private uint _src_playerid = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"src_playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_playerid
    {
      get { return _src_playerid; }
      set { _src_playerid = value; }
    }
    private uint _dest_playerid = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dest_playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_playerid
    {
      get { return _dest_playerid; }
      set { _dest_playerid = value; }
    }
    private uint _dest_level = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dest_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dest_level
    {
      get { return _dest_level; }
      set { _dest_level = value; }
    }
    private uint _headback = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"headback", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headback
    {
      get { return _headback; }
      set { _headback = value; }
    }
    private uint _cur_time = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cur_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_time
    {
      get { return _cur_time; }
      set { _cur_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatPrivateListClientCmd")]
  public partial class ChatPrivateListClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatPrivateListClientCmd() {}
    
    private uint _src_playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"src_playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint src_playerid
    {
      get { return _src_playerid; }
      set { _src_playerid = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ChatPrivateClientCmd> _message = new global::System.Collections.Generic.List<ProtoCmd.ChatPrivateClientCmd>();
    [global::ProtoBuf.ProtoMember(2, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ChatPrivateClientCmd> message
    {
      get { return _message; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatSysClientCmd")]
  public partial class ChatSysClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatSysClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _link_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"link_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_id
    {
      get { return _link_id; }
      set { _link_id = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private string _param1 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _param2 = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatItemShowClientCmd")]
  public partial class ChatItemShowClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatItemShowClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _sendplayerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sendplayerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sendplayerid
    {
      get { return _sendplayerid; }
      set { _sendplayerid = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _itemThisid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"itemThisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> itemThisid
    {
      get { return _itemThisid; }
    }
  
    private string _data = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatReturnItemShowClientCmd")]
  public partial class ChatReturnItemShowClientCmd : global::ProtoBuf.IExtensible
  {
    public ChatReturnItemShowClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> _Items = new global::System.Collections.Generic.List<ProtoCmd.ItemSerialize>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.ItemSerialize> Items
    {
      get { return _Items; }
    }
  
    private ProtoCmd.ErrorCode _errCode = ProtoCmd.ErrorCode.ERR_SUCCESS;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"errCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoCmd.ErrorCode.ERR_SUCCESS)]
    public ProtoCmd.ErrorCode errCode
    {
      get { return _errCode; }
      set { _errCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshWorldChatCountClientCmd")]
  public partial class RefreshWorldChatCountClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshWorldChatCountClientCmd() {}
    
    private uint _max_free_count = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_free_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_free_count
    {
      get { return _max_free_count; }
      set { _max_free_count = value; }
    }
    private uint _cur_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cur_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_count
    {
      get { return _cur_count; }
      set { _cur_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitProblemClientCmd")]
  public partial class SubmitProblemClientCmd : global::ProtoBuf.IExtensible
  {
    public SubmitProblemClientCmd() {}
    
    private uint _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ProtoCmd.ProblemType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoCmd.ProblemType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _phone = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phone
    {
      get { return _phone; }
      set { _phone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitSurveyClientCmd")]
  public partial class SubmitSurveyClientCmd : global::ProtoBuf.IExtensible
  {
    public SubmitSurveyClientCmd() {}
    
    private uint _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ProtoCmd.ActivityType _survey_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"survey_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoCmd.ActivityType survey_type
    {
      get { return _survey_type; }
      set { _survey_type = value; }
    }
    private ProtoCmd.SurveyOption _survey_option;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"survey_option", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoCmd.SurveyOption survey_option
    {
      get { return _survey_option; }
      set { _survey_option = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestChangeChannelIDCmd")]
  public partial class RequestChangeChannelIDCmd : global::ProtoBuf.IExtensible
  {
    public RequestChangeChannelIDCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private uint _channelid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channelid
    {
      get { return _channelid; }
      set { _channelid = value; }
    }
    private uint _newchannelid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"newchannelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint newchannelid
    {
      get { return _newchannelid; }
      set { _newchannelid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespondChangeChannelIDCmd")]
  public partial class RespondChangeChannelIDCmd : global::ProtoBuf.IExtensible
  {
    public RespondChangeChannelIDCmd() {}
    
    private uint _channelid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channelid
    {
      get { return _channelid; }
      set { _channelid = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestChannelInfoClientCmd")]
  public partial class RequestChannelInfoClientCmd : global::ProtoBuf.IExtensible
  {
    public RequestChannelInfoClientCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspChannelInfoClientCmd")]
  public partial class RspChannelInfoClientCmd : global::ProtoBuf.IExtensible
  {
    public RspChannelInfoClientCmd() {}
    
    private uint _channelid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channelid
    {
      get { return _channelid; }
      set { _channelid = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatType_Client")]
    public enum ChatType_Client
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_None", Value=0)]
      ChatType_C_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_All", Value=1)]
      ChatType_C_Client_All = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Nearby", Value=4)]
      ChatType_C_Nearby = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Map", Value=8)]
      ChatType_C_Map = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Danmu", Value=16)]
      ChatType_C_Danmu = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Team", Value=32)]
      ChatType_C_Team = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Army", Value=64)]
      ChatType_C_Army = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Country", Value=128)]
      ChatType_C_Country = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_World", Value=256)]
      ChatType_C_World = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_PrivateChannel", Value=512)]
      ChatType_C_Client_PrivateChannel = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_PrivateWnd", Value=1024)]
      ChatType_C_Client_PrivateWnd = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Client_UsrDefine", Value=2048)]
      ChatType_C_Client_UsrDefine = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Horn", Value=4096)]
      ChatType_C_Horn = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Sociaty", Value=8192)]
      ChatType_C_Sociaty = 8192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_GM", Value=16384)]
      ChatType_C_GM = 16384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Sys", Value=32768)]
      ChatType_C_Sys = 32768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_MsgBox", Value=65536)]
      ChatType_C_MsgBox = 65536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_Center", Value=131072)]
      ChatType_C_Center = 131072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatType_C_GuildWar", Value=262144)]
      ChatType_C_GuildWar = 262144
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProblemType")]
    public enum ProblemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProblemType_Bug", Value=1)]
      ProblemType_Bug = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProblemType_Proposal", Value=2)]
      ProblemType_Proposal = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProblemType_Other", Value=3)]
      ProblemType_Other = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProblemType_Recharge", Value=4)]
      ProblemType_Recharge = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SurveyOption")]
    public enum SurveyOption
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SurveyOption_VerySatisfied", Value=1)]
      SurveyOption_VerySatisfied = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SurveyOption_Satisfied", Value=2)]
      SurveyOption_Satisfied = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SurveyOption_Common", Value=3)]
      SurveyOption_Common = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SurveyOption_DisSatisfied", Value=4)]
      SurveyOption_DisSatisfied = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SurveyOption_VeryDissatisfied", Value=5)]
      SurveyOption_VeryDissatisfied = 5
    }
  
}