//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Command.proto
namespace ProtoCmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CmdNumber")]
    public enum CmdNumber
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientCmdNone", Value=0)]
      ClientCmdNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerVerifyVerLoginClientCmd_C", Value=1)]
      PlayerVerifyVerLoginClientCmd_C = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginAccessLoginClientCmd_C", Value=2)]
      LoginAccessLoginClientCmd_C = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerRequestLoginClientCmd_C", Value=3)]
      PlayerRequestLoginClientCmd_C = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerReturnLoginClientCmd_S", Value=4)]
      ServerReturnLoginClientCmd_S = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerReturnLoginSuccessLoginClientCmd_S", Value=5)]
      ServerReturnLoginSuccessLoginClientCmd_S = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerListSelectClientCmd_S", Value=6)]
      PlayerListSelectClientCmd_S = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckNameSelectClientCmd_CS", Value=7)]
      CheckNameSelectClientCmd_CS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateSelectClientCmd_C", Value=8)]
      CreateSelectClientCmd_C = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateSelectResultClientCmd_S", Value=9)]
      CreateSelectResultClientCmd_S = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginStepSelectClientCmd_S", Value=10)]
      LoginStepSelectClientCmd_S = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRandomRoleNameClientCmd_CS", Value=11)]
      CreateRandomRoleNameClientCmd_CS = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AccountRegisterClientCmd_CS", Value=12)]
      AccountRegisterClientCmd_CS = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTest_CS", Value=14)]
      ReqTest_CS = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqInitDeviceCmd_C", Value=15)]
      ReqInitDeviceCmd_C = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerReturnLoginJsonClientCmd_S", Value=16)]
      ServerReturnLoginJsonClientCmd_S = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspActivateAccountResult_S", Value=17)]
      RspActivateAccountResult_S = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HintClientCmd_S", Value=20)]
      HintClientCmd_S = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspErrorCmd_S", Value=21)]
      RspErrorCmd_S = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestPingClientCmd_C", Value=22)]
      RequestPingClientCmd_C = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondPingClientCmd_S", Value=23)]
      RespondPingClientCmd_S = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReconnectLoginClientCmd_C", Value=24)]
      ReconnectLoginClientCmd_C = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnReconnectLoginClientCmd_S", Value=25)]
      ReturnReconnectLoginClientCmd_S = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendReconnectKeyClientCmd_S", Value=26)]
      SendReconnectKeyClientCmd_S = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqActivateAccountClientCmd_C", Value=27)]
      ReqActivateAccountClientCmd_C = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqChangeCharNameClientCmd_C", Value=28)]
      ReqChangeCharNameClientCmd_C = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspChangeCharNameClientCmd_S", Value=29)]
      RspChangeCharNameClientCmd_S = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateQueueNumClientCmd_S", Value=31)]
      UpdateQueueNumClientCmd_S = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSuspendSyncToClientCommand_S", Value=32)]
      RspSuspendSyncToClientCommand_S = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqExitQueueClientCmd_C", Value=33)]
      ReqExitQueueClientCmd_C = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddItemListItemClientCmd_S", Value=50)]
      AddItemListItemClientCmd_S = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddDataItemClientCmd_S", Value=51)]
      AddDataItemClientCmd_S = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveDataItemClientCmd_CS", Value=52)]
      RemoveDataItemClientCmd_CS = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshCountItemClientCmd_S", Value=56)]
      RefreshCountItemClientCmd_S = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLocationItemClientCmd_S", Value=57)]
      RefreshLocationItemClientCmd_S = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResponseItemOperationItemClientCmd_S", Value=60)]
      ResponseItemOperationItemClientCmd_S = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveResponseClientCmd_S", Value=65)]
      EquipImproveResponseClientCmd_S = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMoneyDataClientCmd_S", Value=91)]
      RefreshMoneyDataClientCmd_S = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoneyChangeClientCmd_S", Value=92)]
      MoneyChangeClientCmd_S = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePlayerMainDataClientCmd_S", Value=93)]
      UpdatePlayerMainDataClientCmd_S = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CharacterDataClientCmd_S", Value=94)]
      CharacterDataClientCmd_S = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoleDataClientCmd_S", Value=106)]
      RoleDataClientCmd_S = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePhysicalClientCmd_S", Value=111)]
      UpdatePhysicalClientCmd_S = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateActivityClientCmd_S", Value=112)]
      UpdateActivityClientCmd_S = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncActivityRewardClientCmd_S", Value=113)]
      SyncActivityRewardClientCmd_S = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncTime_S", Value=115)]
      SyncTime_S = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncTime_C", Value=121)]
      SyncTime_C = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetChargeOrderNumberCmd_C", Value=130)]
      GetChargeOrderNumberCmd_C = 130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetChargeOrderNumberCmd_S", Value=131)]
      RetChargeOrderNumberCmd_S = 131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetTokenCommand_C", Value=141)]
      ReqGetTokenCommand_C = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetTokenCommand_S", Value=142)]
      RspGetTokenCommand_S = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPayForGoodsCommand_C", Value=143)]
      ReqPayForGoodsCommand_C = 143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPayForGoodsCommand_S", Value=144)]
      RspPayForGoodsCommand_S = 144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetChargeResultCommand_C", Value=145)]
      ReqGetChargeResultCommand_C = 145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryPayKeyCommand_C", Value=146)]
      ReqQueryPayKeyCommand_C = 146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryPayKeyCommand_S", Value=147)]
      RspQueryPayKeyCommand_S = 147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPlatSDKInfoCommand_S", Value=148)]
      RspPlatSDKInfoCommand_S = 148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQueryOrderStatusCmd_C", Value=149)]
      ReqQueryOrderStatusCmd_C = 149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQueryOrderStatusCmd_S", Value=150)]
      RspQueryOrderStatusCmd_S = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetChargeResultCommand_S", Value=151)]
      RspGetChargeResultCommand_S = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSyncBalanceCmd_C", Value=152)]
      ReqSyncBalanceCmd_C = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRechargeClientCmd_S", Value=153)]
      RspRechargeClientCmd_S = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondPingClientCmd_C", Value=155)]
      RespondPingClientCmd_C = 155,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestPingClientCmd_S", Value=156)]
      RequestPingClientCmd_S = 156,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMsgClientCmd_S", Value=157)]
      RespondMsgClientCmd_S = 157,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogoutClientCmd_CS", Value=158)]
      LogoutClientCmd_CS = 158,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SortPackageClientCmd_CS", Value=160)]
      SortPackageClientCmd_CS = 160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetPackageGridPackageClientCmd_S", Value=161)]
      SetPackageGridPackageClientCmd_S = 161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExtendCapacityPackageClientCmd_CS", Value=162)]
      ExtendCapacityPackageClientCmd_CS = 162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondMailOperateClientCmd_S", Value=170)]
      RespondMailOperateClientCmd_S = 170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshMailListClientCmd_S", Value=171)]
      RefreshMailListClientCmd_S = 171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadMailClientCmd_C", Value=172)]
      ReadMailClientCmd_C = 172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateMailDataClientCmd_S", Value=173)]
      UpdateMailDataClientCmd_S = 173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PickMailItemClientCmd_C", Value=174)]
      PickMailItemClientCmd_C = 174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMailClientCmd_C", Value=175)]
      SendMailClientCmd_C = 175,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelMailClientCmd_C", Value=176)]
      DelMailClientCmd_C = 176,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultDelMailClientCmd_S", Value=177)]
      ResultDelMailClientCmd_S = 177,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GMChatClientCmd_C", Value=180)]
      GMChatClientCmd_C = 180,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CommonChatClientCmd_S", Value=181)]
      CommonChatClientCmd_S = 181,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatSysClientCmd_S", Value=182)]
      ChatSysClientCmd_S = 182,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatPrivateClientCmd_CS", Value=183)]
      ChatPrivateClientCmd_CS = 183,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatItemShowClientCmd_C", Value=184)]
      ChatItemShowClientCmd_C = 184,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatReturnItemShowClientCmd_S", Value=185)]
      ChatReturnItemShowClientCmd_S = 185,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatTextClientCmd_C", Value=186)]
      ChatTextClientCmd_C = 186,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatReturnTextClientCmd_S", Value=187)]
      ChatReturnTextClientCmd_S = 187,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatOpenPrivateWndClientCmd_CS", Value=188)]
      ChatOpenPrivateWndClientCmd_CS = 188,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshWorldChatCountClientCmd_S", Value=189)]
      RefreshWorldChatCountClientCmd_S = 189,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoticeTipsClientCmd_S", Value=192)]
      NoticeTipsClientCmd_S = 192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestChangeChannelIDCmd_C", Value=193)]
      RequestChangeChannelIDCmd_C = 193,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondChangeChannelIDCmd_S", Value=194)]
      RespondChangeChannelIDCmd_S = 194,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestChannelInfoClientCmd_C", Value=195)]
      RequestChannelInfoClientCmd_C = 195,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspChannelInfoClientCmd_S", Value=196)]
      RspChannelInfoClientCmd_S = 196,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatPrivateListClientCmd_S", Value=197)]
      ChatPrivateListClientCmd_S = 197,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestQuestClientCmd_S", Value=250)]
      SendQuestQuestClientCmd_S = 250,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestElementQuestClientCmd_S", Value=251)]
      SendQuestElementQuestClientCmd_S = 251,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestListQuestClientCmd_S", Value=252)]
      SendQuestListQuestClientCmd_S = 252,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendQuestElementListQuestClientCmd_S", Value=253)]
      SendQuestElementListQuestClientCmd_S = 253,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQuestStateQuestClientCmd_S", Value=254)]
      RefreshQuestStateQuestClientCmd_S = 254,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshQuestElementStateQuestClientCmd_S", Value=255)]
      RefreshQuestElementStateQuestClientCmd_S = 255,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelQuestElementQuestClientCmd_CS", Value=257)]
      DelQuestElementQuestClientCmd_CS = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAcceptQuestElementQuestClientCmd_C", Value=260)]
      RequestAcceptQuestElementQuestClientCmd_C = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishQuestElementQuestClientCmd_C", Value=261)]
      RequestFinishQuestElementQuestClientCmd_C = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuestNotifyQuestClientCmd_S", Value=262)]
      QuestNotifyQuestClientCmd_S = 262,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClearLoopCounterQuestClientCmd_S", Value=263)]
      ClearLoopCounterQuestClientCmd_S = 263,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FindNPCQuestClientCmd_C", Value=264)]
      FindNPCQuestClientCmd_C = 264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshAchievePointListClientCmd_S", Value=265)]
      RefreshAchievePointListClientCmd_S = 265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestSwapSkillClientCmd_C", Value=271)]
      RequestSwapSkillClientCmd_C = 271,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateSkillClientCmd_S", Value=272)]
      UpdateSkillClientCmd_S = 272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSkillLevelUpClientCmd_S", Value=273)]
      RspSkillLevelUpClientCmd_S = 273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveSkillClientCmd_S", Value=274)]
      RemoveSkillClientCmd_S = 274,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchRemovePlayerMapScreenClientCmd_S", Value=300)]
      BatchRemovePlayerMapScreenClientCmd_S = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemovePlayerMapScreenClientCmd_S", Value=301)]
      RemovePlayerMapScreenClientCmd_S = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPlayerMapScreenClientCmd_S", Value=302)]
      AddPlayerMapScreenClientCmd_S = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchAddPlayerMapScreenClientCmd_S", Value=303)]
      BatchAddPlayerMapScreenClientCmd_S = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddMapMapScreenClientCmd_S", Value=304)]
      AddMapMapScreenClientCmd_S = 304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNpcMapScreenClientCmd_S", Value=305)]
      AddNpcMapScreenClientCmd_S = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveNpcMapScreenClientCmd_S", Value=306)]
      RemoveNpcMapScreenClientCmd_S = 306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchRemoveNpcMapScreenClientCmd_S", Value=307)]
      BatchRemoveNpcMapScreenClientCmd_S = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BatchAddNpcMapScreenClientCmd_S", Value=308)]
      BatchAddNpcMapScreenClientCmd_S = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetPlayerMoveClientCmd_S", Value=336)]
      RetPlayerMoveClientCmd_S = 336,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerMoveFailClientCmd_S", Value=337)]
      PlayerMoveFailClientCmd_S = 337,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcEndMoveClientCmd_S", Value=340)]
      NpcEndMoveClientCmd_S = 340,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerNpcMoveClientCmd_S", Value=341)]
      ServerNpcMoveClientCmd_S = 341,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcShiftMoveClientCmd_S", Value=346)]
      NpcShiftMoveClientCmd_S = 346,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerShiftMoveClientCmd_S", Value=347)]
      PlayerShiftMoveClientCmd_S = 347,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshStoryListClientCmd_S", Value=450)]
      RefreshStoryListClientCmd_S = 450,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishStoryClientCmd_C", Value=451)]
      RequestFinishStoryClientCmd_C = 451,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFinishStoryClientCmd_S", Value=452)]
      AddFinishStoryClientCmd_S = 452,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddDoingStoryClientCmd_S", Value=453)]
      AddDoingStoryClientCmd_S = 453,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncMpCmd_S", Value=595)]
      SyncMpCmd_S = 595,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestLeaveFbClientCmd_C", Value=602)]
      RequestLeaveFbClientCmd_C = 602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FbSettlementDataCmd_S", Value=603)]
      FbSettlementDataCmd_S = 603,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FbBattleFieldSettlementDataCmd_S", Value=604)]
      FbBattleFieldSettlementDataCmd_S = 604,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCastSkillClientCmd_S", Value=607)]
      RspCastSkillClientCmd_S = 607,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendDelBuffCmd_S", Value=612)]
      SendDelBuffCmd_S = 612,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncReliveCmd_S", Value=611)]
      SyncReliveCmd_S = 611,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateBuffTimeCmd_S", Value=613)]
      UpdateBuffTimeCmd_S = 613,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncMaxHpCmd_S", Value=614)]
      SyncMaxHpCmd_S = 614,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncHpCmd_S", Value=615)]
      SyncHpCmd_S = 615,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncShieldCmd_S", Value=616)]
      SyncShieldCmd_S = 616,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncBuffCmd_S", Value=617)]
      SyncBuffCmd_S = 617,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFightPropCmd_S", Value=620)]
      UpdateFightPropCmd_S = 620,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLeaveFbClientCmd_S", Value=621)]
      RspLeaveFbClientCmd_S = 621,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendBattleFieldScore_S", Value=622)]
      SendBattleFieldScore_S = 622,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendFbCamp_S", Value=623)]
      SendFbCamp_S = 623,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendWarRuneCmd_S", Value=624)]
      SendWarRuneCmd_S = 624,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSkillCoolTimeCmd_S", Value=625)]
      RefreshSkillCoolTimeCmd_S = 625,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPlayerFlagCmd_S", Value=643)]
      SendPlayerFlagCmd_S = 643,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncCharacterFlagClientCmd_S", Value=644)]
      SyncCharacterFlagClientCmd_S = 644,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendFriendInfoClientCmd_S", Value=645)]
      SendFriendInfoClientCmd_S = 645,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestViewPlayerInfoRankClientCmd_C", Value=648)]
      RequestViewPlayerInfoRankClientCmd_C = 648,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnViewPlayerInfoRankClientCmd_S", Value=649)]
      ReturnViewPlayerInfoRankClientCmd_S = 649,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestViewPlayerInfoClientCmd_C", Value=650)]
      RequestViewPlayerInfoClientCmd_C = 650,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnViewPlayerInfoClientCmd_S", Value=651)]
      ReturnViewPlayerInfoClientCmd_S = 651,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RespondFriendOperateClientCmd_S", Value=652)]
      RespondFriendOperateClientCmd_S = 652,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFriendListClientCmd_C", Value=653)]
      RequestFriendListClientCmd_C = 653,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshFriendListClientCmd_S", Value=654)]
      RefreshFriendListClientCmd_S = 654,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateFriendDataClientCmd_S", Value=655)]
      UpdateFriendDataClientCmd_S = 655,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendInviteClientCmd_C", Value=656)]
      FriendInviteClientCmd_C = 656,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelFriendInviteClientCmd_C", Value=657)]
      CancelFriendInviteClientCmd_C = 657,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AgreeFriendApplyClientCmd_C", Value=658)]
      AgreeFriendApplyClientCmd_C = 658,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestDelFriendClientCmd_C", Value=659)]
      RequestDelFriendClientCmd_C = 659,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultDelFriendClientCmd_S", Value=660)]
      ResultDelFriendClientCmd_S = 660,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFriendInviteClientCmd_S", Value=661)]
      AddFriendInviteClientCmd_S = 661,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelFriendInviteClientCmd_S", Value=662)]
      DelFriendInviteClientCmd_S = 662,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddFriendApplyClientCmd_S", Value=663)]
      AddFriendApplyClientCmd_S = 663,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelFriendApplyClientCmd_S", Value=664)]
      DelFriendApplyClientCmd_S = 664,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FriendOnlineClientCmd_S", Value=665)]
      FriendOnlineClientCmd_S = 665,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FindPlayerClientCmd_C", Value=666)]
      FindPlayerClientCmd_C = 666,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindPlayerClientCmd_S", Value=667)]
      RspFindPlayerClientCmd_S = 667,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PresentGiftClientCmd_C", Value=668)]
      PresentGiftClientCmd_C = 668,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestViewPlayerRoomInfoClientCmd_C", Value=689)]
      RequestViewPlayerRoomInfoClientCmd_C = 689,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReturnViewPlayerRoomInfoClientCmd_S", Value=690)]
      ReturnViewPlayerRoomInfoClientCmd_S = 690,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshSpaceDanMuListClientCmd_S", Value=692)]
      RefreshSpaceDanMuListClientCmd_S = 692,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPlayerSpaceDanMuClientCmd_C", Value=693)]
      AddPlayerSpaceDanMuClientCmd_C = 693,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelPlayerSpaceDanMuClientCmd_C", Value=695)]
      DelPlayerSpaceDanMuClientCmd_C = 695,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAddFriendshipClientCmd_C", Value=696)]
      RequestAddFriendshipClientCmd_C = 696,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultAddFriendshipClientCmd_S", Value=697)]
      ResultAddFriendshipClientCmd_S = 697,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAgreeFriendshipClientCmd_C", Value=698)]
      RequestAgreeFriendshipClientCmd_C = 698,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultAgreeFriendshipClientCmd_S", Value=699)]
      ResultAgreeFriendshipClientCmd_S = 699,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HandleFriendlyClientCmd_C", Value=700)]
      HandleFriendlyClientCmd_C = 700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeFriendNickNameClientCmd_C", Value=701)]
      ChangeFriendNickNameClientCmd_C = 701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerTransMapCmd_C", Value=709)]
      PlayerTransMapCmd_C = 709,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeClientCmd_S", Value=717)]
      RechargeClientCmd_S = 717,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdataFirstRechargeClientCmd_S", Value=718)]
      UpdataFirstRechargeClientCmd_S = 718,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RechargeRelateClientCmd_S", Value=719)]
      RechargeRelateClientCmd_S = 719,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendMonsterDataFinishClientCmd_S", Value=781)]
      SendMonsterDataFinishClientCmd_S = 781,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPlayerDataFinishClientCmd_S", Value=787)]
      SendPlayerDataFinishClientCmd_S = 787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestReliveClientCmd_C", Value=803)]
      RequestReliveClientCmd_C = 803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RelivePlayerDeathClienCmd_S", Value=804)]
      RelivePlayerDeathClienCmd_S = 804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RelivePlayerFailClientCmd_S", Value=808)]
      RelivePlayerFailClientCmd_S = 808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PraiseClientCmd_C", Value=850)]
      PraiseClientCmd_C = 850,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateNewsDataClientCmd_S", Value=851)]
      UpdateNewsDataClientCmd_S = 851,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeleteNewsClientCmd_S", Value=852)]
      DeleteNewsClientCmd_S = 852,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestRecommendFriendClientCmd_C", Value=853)]
      RequestRecommendFriendClientCmd_C = 853,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshRecommendFriendClientCmd_S", Value=854)]
      RefreshRecommendFriendClientCmd_S = 854,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelRecommendFriendClientCmd_S", Value=855)]
      DelRecommendFriendClientCmd_S = 855,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddPlayerCmd_S", Value=1052)]
      RspAddPlayerCmd_S = 1052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRemovePlayerCmd_S", Value=1053)]
      RspRemovePlayerCmd_S = 1053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestRelivePlayerDeathReliveClientCmd_C", Value=1230)]
      RequestRelivePlayerDeathReliveClientCmd_C = 1230,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAddBlacklistClientCmd_C", Value=1880)]
      RequestAddBlacklistClientCmd_C = 1880,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestDelBlacklistClientCmd_C", Value=1881)]
      RequestDelBlacklistClientCmd_C = 1881,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultAddBlacklistClientCmd_S", Value=1882)]
      ResultAddBlacklistClientCmd_S = 1882,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResultDelBlacklistClientCmd_S", Value=1883)]
      ResultDelBlacklistClientCmd_S = 1883,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestSetFriendTagClientCmd_C", Value=1884)]
      RequestSetFriendTagClientCmd_C = 1884,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendLetterClientCmd_S", Value=1909)]
      SendLetterClientCmd_S = 1909,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TravelSettleClientCmd_S", Value=1910)]
      TravelSettleClientCmd_S = 1910,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AngryHomeTravelClientCmd_S", Value=1913)]
      AngryHomeTravelClientCmd_S = 1913,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBuyBindDiamondClientCmd_C", Value=1923)]
      ReqBuyBindDiamondClientCmd_C = 1923,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshLinkClientCmd_S", Value=1925)]
      RefreshLinkClientCmd_S = 1925,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGiveGiftClientCmd_C", Value=1926)]
      ReqGiveGiftClientCmd_C = 1926,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCollisionClientCmd_C", Value=1927)]
      ReqCollisionClientCmd_C = 1927,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshCharacterFormClientCmd_S", Value=1928)]
      RefreshCharacterFormClientCmd_S = 1928,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBuyFashionClientCmd_C", Value=1929)]
      ReqBuyFashionClientCmd_C = 1929,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspBuyFashionClientCmd_S", Value=1930)]
      RspBuyFashionClientCmd_S = 1930,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetInfoClientCmd_S", Value=1933)]
      RspGetInfoClientCmd_S = 1933,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteFormClientCmd_CS", Value=1936)]
      CompleteFormClientCmd_CS = 1936,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WaitSyncSettleInfo_S", Value=1947)]
      WaitSyncSettleInfo_S = 1947,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnlockInstanceAchieve_S", Value=1949)]
      UnlockInstanceAchieve_S = 1949,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendInstanceAchieveInfo_S", Value=1950)]
      SendInstanceAchieveInfo_S = 1950,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncWorldFlagCmd_S", Value=1966)]
      SyncWorldFlagCmd_S = 1966,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewCardInfoCmd_S", Value=1967)]
      NewCardInfoCmd_S = 1967,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateInstanceAchieveInfo_S", Value=1968)]
      UpdateInstanceAchieveInfo_S = 1968,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRoomCardInfoCmd_C", Value=1971)]
      ReqRoomCardInfoCmd_C = 1971,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRoomCardInfoCmd_S", Value=1972)]
      RspRoomCardInfoCmd_S = 1972,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUpdateOnlineTimeCmd_S", Value=1977)]
      RspUpdateOnlineTimeCmd_S = 1977,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshHeadInfoCmd_S", Value=1978)]
      RefreshHeadInfoCmd_S = 1978,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddHeadInfoCmd_S", Value=1979)]
      AddHeadInfoCmd_S = 1979,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeleteNodeCmd_S", Value=1985)]
      DeleteNodeCmd_S = 1985,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActiveNodeCmd_S", Value=1986)]
      ActiveNodeCmd_S = 1986,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqEnterPlotSectionCmd_C", Value=1987)]
      ReqEnterPlotSectionCmd_C = 1987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPlotListClientCmd_S", Value=1991)]
      SendPlotListClientCmd_S = 1991,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPlotDataClientCmd_S", Value=1992)]
      RefreshPlotDataClientCmd_S = 1992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectAidCardClientCmd_CS", Value=1995)]
      SelectAidCardClientCmd_CS = 1995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendAidInfoCmd_S", Value=1996)]
      SendAidInfoCmd_S = 1996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AidPlayerInfoCmd_S", Value=1997)]
      AidPlayerInfoCmd_S = 1997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLotteryCardClientCmd_C", Value=2000)]
      ReqLotteryCardClientCmd_C = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLotteryCardClientCmd_S", Value=2001)]
      RspLotteryCardClientCmd_S = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendAllStoreGoodsClientCmd_S", Value=2002)]
      SendAllStoreGoodsClientCmd_S = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshStoreGoodsClientCmd_S", Value=2003)]
      RefreshStoreGoodsClientCmd_S = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspBuyGoodsClientCmd_S", Value=2004)]
      RspBuyGoodsClientCmd_S = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBuyGoodsClientCmd_C", Value=2005)]
      ReqBuyGoodsClientCmd_C = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAllStoreGoodsClientCmd_C", Value=2006)]
      ReqAllStoreGoodsClientCmd_C = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspBuyMonthCardClientCmd_S", Value=2007)]
      RspBuyMonthCardClientCmd_S = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBuyMonthCardClientCmd_C", Value=2008)]
      ReqBuyMonthCardClientCmd_C = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqMonthCardAwardClientCmd_C", Value=2009)]
      ReqMonthCardAwardClientCmd_C = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspMonthCardAwardClientCmd_S", Value=2010)]
      RspMonthCardAwardClientCmd_S = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspEquipImproveClientCmd_S", Value=2011)]
      RspEquipImproveClientCmd_S = 2011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipImproveClientCmd_C", Value=2012)]
      EquipImproveClientCmd_C = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAwakenCmd_C", Value=2013)]
      ReqAwakenCmd_C = 2013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAwakenCmd_S", Value=2014)]
      RspAwakenCmd_S = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAwakenAwardCmd_C", Value=2015)]
      ReqAwakenAwardCmd_C = 2015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAwakenAwardCmd_S", Value=2016)]
      RspAwakenAwardCmd_S = 2016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRetireClientCmd_CS", Value=2017)]
      ReqRetireClientCmd_CS = 2017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestEnterFbClientCmd_C", Value=2018)]
      RequestEnterFbClientCmd_C = 2018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddCharExpClientCmd_CS", Value=2019)]
      AddCharExpClientCmd_CS = 2019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetAddExpTipClientCmd_C", Value=2020)]
      SetAddExpTipClientCmd_C = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendLoadedSceneClientCmd_C", Value=2021)]
      SendLoadedSceneClientCmd_C = 2021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcceptRankUpTaskClientCmd_C", Value=2022)]
      AcceptRankUpTaskClientCmd_C = 2022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteRankUpClientCmd_CS", Value=2023)]
      CompleteRankUpClientCmd_CS = 2023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateLevelExpDataClientCmd_S", Value=2024)]
      UpdateLevelExpDataClientCmd_S = 2024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LostSingleFbClientCmd_C", Value=2025)]
      LostSingleFbClientCmd_C = 2025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqEnterSceneCmd_C", Value=2026)]
      ReqEnterSceneCmd_C = 2026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncSingleFbSettleInfo_C", Value=2027)]
      SyncSingleFbSettleInfo_C = 2027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillMonsterClientCmd_C", Value=2028)]
      KillMonsterClientCmd_C = 2028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterPlotChapterClientCmd_CS", Value=2029)]
      EnterPlotChapterClientCmd_CS = 2029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompletePlotChapterClientCmd_C", Value=2030)]
      CompletePlotChapterClientCmd_C = 2030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkipPlotSectionClientCmd_C", Value=2031)]
      SkipPlotSectionClientCmd_C = 2031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillAllMonsterClientCmd_C", Value=2032)]
      KillAllMonsterClientCmd_C = 2032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwapHeadIndexClientCmd_CS", Value=2033)]
      SwapHeadIndexClientCmd_CS = 2033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SwapHeadBackClientCmd_CS", Value=2034)]
      SwapHeadBackClientCmd_CS = 2034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStoryAwardClientCmd_CS", Value=2035)]
      ReqStoryAwardClientCmd_CS = 2035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveItemClientCmd_C", Value=2036)]
      MoveItemClientCmd_C = 2036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnionMoveItemClientCmd_C", Value=2037)]
      UnionMoveItemClientCmd_C = 2037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPickAllMailData_C", Value=2038)]
      ReqPickAllMailData_C = 2038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPickMailData_C", Value=2039)]
      ReqPickMailData_C = 2039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestSkillLevelUpClientCmd_C", Value=2040)]
      RequestSkillLevelUpClientCmd_C = 2040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UsePhyscialItemClientCmd_CS", Value=2041)]
      UsePhyscialItemClientCmd_CS = 2041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyPhyscialClientCmd_CS", Value=2042)]
      BuyPhyscialClientCmd_CS = 2042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DelQuestQuestClientCmd_CS", Value=2043)]
      DelQuestQuestClientCmd_CS = 2043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestAcceptQuestQuestClientCmd_C", Value=2044)]
      RequestAcceptQuestQuestClientCmd_C = 2044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RequestFinishQuestQuestClientCmd_C", Value=2045)]
      RequestFinishQuestQuestClientCmd_C = 2045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetRoleInRoomClientCmd_C", Value=2046)]
      SetRoleInRoomClientCmd_C = 2046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUpdateDanmuSwitchCmd_C", Value=2047)]
      ReqUpdateDanmuSwitchCmd_C = 2047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFreshPlayerCmd_CS", Value=2048)]
      ReqFreshPlayerCmd_CS = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetViewRoomFlagClientCmd_C", Value=2049)]
      SetViewRoomFlagClientCmd_C = 2049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetSpaceMoodClientCmd_C", Value=2050)]
      SetSpaceMoodClientCmd_C = 2050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSmallPacketClientCmd_C", Value=2051)]
      ReqSmallPacketClientCmd_C = 2051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSmallPacketClientCmd_S", Value=2052)]
      RspSmallPacketClientCmd_S = 2052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGuideSystemClientCmd_C", Value=2053)]
      ReqGuideSystemClientCmd_C = 2053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGuideSystemClientCmd_S", Value=2054)]
      RspGuideSystemClientCmd_S = 2054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTravelClientCmd_C", Value=2055)]
      ReqTravelClientCmd_C = 2055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspTravelClientCmd_S", Value=2056)]
      RspTravelClientCmd_S = 2056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSwapCardFaceCmd_CS", Value=2057)]
      ReqSwapCardFaceCmd_CS = 2057,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerMoveClientCmd_C", Value=2058)]
      PlayerMoveClientCmd_C = 2058,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NpcMoveClientCmd_C", Value=2059)]
      NpcMoveClientCmd_C = 2059,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendTriggerEffectCmd_S", Value=2060)]
      SendTriggerEffectCmd_S = 2060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRoleLinkClientCmd_C", Value=2061)]
      ReqRoleLinkClientCmd_C = 2061,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRoleLinkClientCmd_S", Value=2062)]
      RspRoleLinkClientCmd_S = 2062,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddRoleLinkClientCmd_C", Value=2063)]
      ReqAddRoleLinkClientCmd_C = 2063,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddRoleLinkExpClientCmd_C", Value=2064)]
      ReqAddRoleLinkExpClientCmd_C = 2064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseSkillClientCmd_C", Value=2065)]
      UseSkillClientCmd_C = 2065,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CastSkillClientCmd_C", Value=2066)]
      CastSkillClientCmd_C = 2066,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TriggerSkillEffectClientCmd_CS", Value=2067)]
      TriggerSkillEffectClientCmd_CS = 2067,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FinishSkillClientCmd_C", Value=2068)]
      FinishSkillClientCmd_C = 2068,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRoleLinkUpGradeClientCmd_S", Value=2069)]
      RspRoleLinkUpGradeClientCmd_S = 2069,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendTriggerAreaClientCmd_C", Value=2070)]
      SendTriggerAreaClientCmd_C = 2070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FinishNodeClientCmd_C", Value=2071)]
      FinishNodeClientCmd_C = 2071,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqChooseCardClientCmd_C", Value=2072)]
      ReqChooseCardClientCmd_C = 2072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspChooseCardClientCmd_S", Value=2073)]
      RspChooseCardClientCmd_S = 2073,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetPrepareTeamCmd_CS", Value=2074)]
      SetPrepareTeamCmd_CS = 2074,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLotteryPoolsCmd_C", Value=2075)]
      ReqLotteryPoolsCmd_C = 2075,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLotteryPoolsCmd_S", Value=2076)]
      RspLotteryPoolsCmd_S = 2076,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetSectionAwardClientCmd_C", Value=2077)]
      ReqGetSectionAwardClientCmd_C = 2077,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetSectionAwardClientCmd_S", Value=2078)]
      RspGetSectionAwardClientCmd_S = 2078,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetInstanceInfoClientCmd_S", Value=2079)]
      RspGetInstanceInfoClientCmd_S = 2079,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqQuestionnaireRewardClientCmd_C", Value=2080)]
      ReqQuestionnaireRewardClientCmd_C = 2080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetInstanceSettleClientCmd_S", Value=2081)]
      RspGetInstanceSettleClientCmd_S = 2081,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBreakthroughClientCmd_C", Value=2082)]
      ReqBreakthroughClientCmd_C = 2082,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTravelInfoClientCmd_C", Value=2083)]
      ReqTravelInfoClientCmd_C = 2083,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendTravelInfoClientCmd_S", Value=2084)]
      SendTravelInfoClientCmd_S = 2084,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FinishTravelClientCmd_CS", Value=2085)]
      FinishTravelClientCmd_CS = 2085,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetTravelReportCmd_S", Value=2086)]
      GetTravelReportCmd_S = 2086,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqTravelReportClientCmd_CS", Value=2087)]
      ReqTravelReportClientCmd_CS = 2087,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspBreakthroughClientCmd_S", Value=2088)]
      RspBreakthroughClientCmd_S = 2088,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RecallTravelClientCmd_CS", Value=2089)]
      RecallTravelClientCmd_CS = 2089,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshEnergyClientCmd_S", Value=2090)]
      RefreshEnergyClientCmd_S = 2090,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGardenInfoClientCmd_C", Value=2091)]
      ReqGardenInfoClientCmd_C = 2091,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGardenInfoClientCmd_S", Value=2092)]
      RspGardenInfoClientCmd_S = 2092,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlantedClientCmd_C", Value=2093)]
      ReqPlantedClientCmd_C = 2093,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspLandInfoClientCmd_S", Value=2094)]
      RspLandInfoClientCmd_S = 2094,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlantedSpeedClientCmd_CS", Value=2095)]
      PlantedSpeedClientCmd_CS = 2095,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqHarvestClientCmd_C", Value=2096)]
      ReqHarvestClientCmd_C = 2096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspHarvestClientCmd_S", Value=2097)]
      RspHarvestClientCmd_S = 2097,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnlockLandClientCmd_CS", Value=2098)]
      UnlockLandClientCmd_CS = 2098,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBackyardInfoClientCmd_C", Value=2099)]
      ReqBackyardInfoClientCmd_C = 2099,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspBackyardInfoClientCmd_S", Value=2100)]
      RspBackyardInfoClientCmd_S = 2100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUnLockRoomClientCmd_CS", Value=2101)]
      ReqUnLockRoomClientCmd_CS = 2101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReplaceFurnitureClientCmd_C", Value=2103)]
      ReqReplaceFurnitureClientCmd_C = 2103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspReplaceFurnitureClientCmd_S", Value=2104)]
      RspReplaceFurnitureClientCmd_S = 2104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlowlandClientCmd_CS", Value=2105)]
      ReqPlowlandClientCmd_CS = 2105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUnlockFurnitureClientCmd_CS", Value=2106)]
      ReqUnlockFurnitureClientCmd_CS = 2106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqKitchenInfoClientCmd_C", Value=2107)]
      ReqKitchenInfoClientCmd_C = 2107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspKitchenInfoClientCmd_S", Value=2108)]
      RspKitchenInfoClientCmd_S = 2108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCookClientCmd_C", Value=2109)]
      ReqCookClientCmd_C = 2109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCookClientCmd_S", Value=2110)]
      RspCookClientCmd_S = 2110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqOndutyClientCmd_CS", Value=2111)]
      ReqOndutyClientCmd_CS = 2111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCollectRoleBehaviorClientCmd_C", Value=2112)]
      ReqCollectRoleBehaviorClientCmd_C = 2112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGameRoleSkinInfoClientCmd_C", Value=2113)]
      ReqGameRoleSkinInfoClientCmd_C = 2113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGameRoleSkinInfoClientCmd_S", Value=2114)]
      RspGameRoleSkinInfoClientCmd_S = 2114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SaveCurrentSkinClientCmd_CS", Value=2115)]
      SaveCurrentSkinClientCmd_CS = 2115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRedeemSkinClientCmd_CS", Value=2116)]
      ReqRedeemSkinClientCmd_CS = 2116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SetAidCardClientCmd_CS", Value=2117)]
      SetAidCardClientCmd_CS = 2117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActiveAidCardClientCmd_CS", Value=2118)]
      ActiveAidCardClientCmd_CS = 2118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetCelebrityRankInfoClientCmd_C", Value=2119)]
      ReqGetCelebrityRankInfoClientCmd_C = 2119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetCelebrityRankInfoClientCmd_S", Value=2120)]
      RspGetCelebrityRankInfoClientCmd_S = 2120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendPrepareTeamClientCmd_S", Value=2121)]
      SendPrepareTeamClientCmd_S = 2121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCelebrityRankInfoClientCmd_S", Value=2122)]
      RspCelebrityRankInfoClientCmd_S = 2122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAidCardInfoClientCmd_S", Value=2123)]
      RspAidCardInfoClientCmd_S = 2123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExchangePresentsClientCmd_CS", Value=2124)]
      ExchangePresentsClientCmd_CS = 2124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAidCardListClientCmd_C", Value=2125)]
      ReqAidCardListClientCmd_C = 2125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAidCardListClientCmd_S", Value=2126)]
      RspAidCardListClientCmd_S = 2126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetTreasurePointAwardClientCmd_C", Value=2127)]
      ReqGetTreasurePointAwardClientCmd_C = 2127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGetTreasurePointAwardClientCmd_S", Value=2128)]
      RspGetTreasurePointAwardClientCmd_S = 2128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspTaskLevelStatusClientCmd_S", Value=2129)]
      RspTaskLevelStatusClientCmd_S = 2129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqChangeMainYardMapIdClientCmd_CS", Value=2130)]
      ReqChangeMainYardMapIdClientCmd_CS = 2130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CheckAllMainYardMapIdClientCmd_CS", Value=2131)]
      CheckAllMainYardMapIdClientCmd_CS = 2131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnLockMainYardMapIdClientCmd_CS", Value=2132)]
      UnLockMainYardMapIdClientCmd_CS = 2132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGetPhyscialPowerClientCmd_C", Value=2133)]
      ReqGetPhyscialPowerClientCmd_C = 2133,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStartPlantedClientCmd_C", Value=2134)]
      ReqStartPlantedClientCmd_C = 2134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSaveLastReferLinkClientCmd_C", Value=2135)]
      ReqSaveLastReferLinkClientCmd_C = 2135,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DebrisAwakenCardClientCmd_CS", Value=2136)]
      DebrisAwakenCardClientCmd_CS = 2136,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqActiveRewardClientCmd_C", Value=2137)]
      ReqActiveRewardClientCmd_C = 2137,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBackYardRoomInfoClientCmd_CS", Value=2138)]
      ReqBackYardRoomInfoClientCmd_CS = 2138,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBackYardRoomUnLockClientCmd_CS", Value=2139)]
      ReqBackYardRoomUnLockClientCmd_CS = 2139,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoleSkillRewardClientCmd_CS", Value=2140)]
      GetRoleSkillRewardClientCmd_CS = 2140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReceiveComfortAwardInfoClientCmd_CS", Value=2141)]
      ReqReceiveComfortAwardInfoClientCmd_CS = 2141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReceiveComfortAwardClientCmd_CS", Value=2142)]
      ReqReceiveComfortAwardClientCmd_CS = 2142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBackYardBenchInfoClientCmd_CS", Value=2143)]
      ReqBackYardBenchInfoClientCmd_CS = 2143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqBackYardBenchUpgradeClientCmd_CS", Value=2144)]
      ReqBackYardBenchUpgradeClientCmd_CS = 2144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SignInClientCmd_CS", Value=2145)]
      SignInClientCmd_CS = 2145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncSignInInfoClientCmd_S", Value=2146)]
      SyncSignInInfoClientCmd_S = 2146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshActivityListClientCmd_S", Value=2147)]
      RefreshActivityListClientCmd_S = 2147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncPaperInfoClientCmd_S", Value=2148)]
      SyncPaperInfoClientCmd_S = 2148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncSignInDaysInfoClientCmd_S", Value=2149)]
      SyncSignInDaysInfoClientCmd_S = 2149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendActivityRankClientCmd_S", Value=2150)]
      SendActivityRankClientCmd_S = 2150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendRoleBehaviourUnlockClientCmd_S", Value=2151)]
      SendRoleBehaviourUnlockClientCmd_S = 2151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PushRandomEventInfoClientCmd_S", Value=2152)]
      PushRandomEventInfoClientCmd_S = 2152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DealRandomEventStepClientCmd_CS", Value=2153)]
      DealRandomEventStepClientCmd_CS = 2153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCourtyardInfoClientCmd_C", Value=2154)]
      ReqCourtyardInfoClientCmd_C = 2154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCourtyardInfoClientCmd_S", Value=2155)]
      RspCourtyardInfoClientCmd_S = 2155,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqManufactureFurnitureClientCmd_C", Value=2156)]
      ReqManufactureFurnitureClientCmd_C = 2156,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspManufactureFurnitureClientCmd_S", Value=2157)]
      RspManufactureFurnitureClientCmd_S = 2157,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpgradeFurnitureClientCmd_CS", Value=2158)]
      UpgradeFurnitureClientCmd_CS = 2158,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnlockFurnitureClientCmd_S", Value=2159)]
      UnlockFurnitureClientCmd_S = 2159,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRecordTimesClientCmd_CS", Value=2160)]
      ReqRecordTimesClientCmd_CS = 2160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdatePlayerFriendlyClientCmd_S", Value=2161)]
      UpdatePlayerFriendlyClientCmd_S = 2161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFirstGuildClientCmd_S", Value=2162)]
      RspFirstGuildClientCmd_S = 2162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspNewBieStepClientCmd_S", Value=2163)]
      RspNewBieStepClientCmd_S = 2163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqStartNewBieStepClientCmd_C", Value=2164)]
      ReqStartNewBieStepClientCmd_C = 2164,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFinishNewBieStepClientCmd_C", Value=2165)]
      ReqFinishNewBieStepClientCmd_C = 2165,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BindAccountClientCmd_C", Value=2166)]
      BindAccountClientCmd_C = 2166,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCheckMailAttachData_C", Value=2167)]
      ReqCheckMailAttachData_C = 2167,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFinishAllQuestClientCmd_C", Value=2168)]
      ReqFinishAllQuestClientCmd_C = 2168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefineDeskInitInfoClientCmd_S", Value=2169)]
      RefineDeskInitInfoClientCmd_S = 2169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefineDeskLvClientCmd_S", Value=2170)]
      RefineDeskLvClientCmd_S = 2170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRefineClientCmd_C", Value=2171)]
      ReqRefineClientCmd_C = 2171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRefineStateClientCmd_S", Value=2172)]
      RspRefineStateClientCmd_S = 2172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqEndRefineClientCmd_C", Value=2173)]
      ReqEndRefineClientCmd_C = 2173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSpeedUpRefineClientCmd_C", Value=2174)]
      ReqSpeedUpRefineClientCmd_C = 2174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRecvRefineItemClientCmd_C", Value=2175)]
      ReqRecvRefineItemClientCmd_C = 2175,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelSuspendGmClientCmd_C", Value=5000)]
      ReqDelSuspendGmClientCmd_C = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelSuspendGmClientCmd_S", Value=5001)]
      RspDelSuspendGmClientCmd_S = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelNoticeGmClientCmd_C", Value=5002)]
      ReqDelNoticeGmClientCmd_C = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelNoticeGmClientCmd_S", Value=5003)]
      RspDelNoticeGmClientCmd_S = 5003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUserLoginGmClientCmd_C", Value=5004)]
      ReqUserLoginGmClientCmd_C = 5004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUserLoginGmClientCmd_S", Value=5005)]
      RspUserLoginGmClientCmd_S = 5005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspConnectGmClientCmd_S", Value=5006)]
      RspConnectGmClientCmd_S = 5006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindPlayerGmClientCmd_C", Value=5007)]
      ReqFindPlayerGmClientCmd_C = 5007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindPlayerGmClientCmd_S", Value=5008)]
      RspFindPlayerGmClientCmd_S = 5008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindPlayerListGmClientCmd_C", Value=5009)]
      ReqFindPlayerListGmClientCmd_C = 5009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindPlayerListGmClientCmd_S", Value=5010)]
      RspFindPlayerListGmClientCmd_S = 5010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindSuspendGmClientCmd_C", Value=5011)]
      ReqFindSuspendGmClientCmd_C = 5011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindSuspendGmClientCmd_S", Value=5012)]
      RspFindSuspendGmClientCmd_S = 5012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddSuspendGmClientCmd_C", Value=5013)]
      ReqAddSuspendGmClientCmd_C = 5013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddSuspendGmClientCmd_S", Value=5014)]
      RspAddSuspendGmClientCmd_S = 5014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindNoticeGmClientCmd_C", Value=5015)]
      ReqFindNoticeGmClientCmd_C = 5015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindNoticeGmClientCmd_S", Value=5016)]
      RspFindNoticeGmClientCmd_S = 5016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddNoticeGmClientCmd_C", Value=5017)]
      ReqAddNoticeGmClientCmd_C = 5017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddNoticeGmClientCmd_S", Value=5018)]
      RspAddNoticeGmClientCmd_S = 5018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqReloadGmServerGmClientCmd_C", Value=5019)]
      ReqReloadGmServerGmClientCmd_C = 5019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddActivityGmClientCmd_C", Value=5021)]
      ReqAddActivityGmClientCmd_C = 5021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddActivityGmClientCmd_S", Value=5022)]
      RspAddActivityGmClientCmd_S = 5022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelActivityGmClientCmd_C", Value=5023)]
      ReqDelActivityGmClientCmd_C = 5023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelActivityGmClientCmd_S", Value=5024)]
      RspDelActivityGmClientCmd_S = 5024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqActivityListGmClientCmd_C", Value=5025)]
      ReqActivityListGmClientCmd_C = 5025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspActivityListGmClientCmd_S", Value=5026)]
      RspActivityListGmClientCmd_S = 5026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqViewActivityGmClientCmd_C", Value=5027)]
      ReqViewActivityGmClientCmd_C = 5027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspViewActivityGmClientCmd_S", Value=5028)]
      RspViewActivityGmClientCmd_S = 5028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqGmCommandGmClientCmd_C", Value=5030)]
      ReqGmCommandGmClientCmd_C = 5030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspGmCommandGmClientCmd_S", Value=5031)]
      RspGmCommandGmClientCmd_S = 5031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSendMailGmClientCmd_C", Value=5032)]
      ReqSendMailGmClientCmd_C = 5032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSendMailGmClientCmd_S", Value=5033)]
      RspSendMailGmClientCmd_S = 5033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddGmAccountGmClientCmd_C", Value=5035)]
      ReqAddGmAccountGmClientCmd_C = 5035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddGmAccountGmClientCmd_S", Value=5036)]
      RspAddGmAccountGmClientCmd_S = 5036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqModGmAccountGmClientCmd_C", Value=5037)]
      ReqModGmAccountGmClientCmd_C = 5037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspModGmAccountGmClientCmd_S", Value=5038)]
      RspModGmAccountGmClientCmd_S = 5038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindGmAccountGmClientCmd_C", Value=5039)]
      ReqFindGmAccountGmClientCmd_C = 5039,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindGmAccountGmClientCmd_S", Value=5040)]
      RspFindGmAccountGmClientCmd_S = 5040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqModGmAccountPasswdGmClientCmd_C", Value=5041)]
      ReqModGmAccountPasswdGmClientCmd_C = 5041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SendServerInfoGmClientCmd_S", Value=5042)]
      SendServerInfoGmClientCmd_S = 5042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqFindGmLogGmClientCmd_C", Value=5043)]
      ReqFindGmLogGmClientCmd_C = 5043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFindGmLogGmClientCmd_S", Value=5044)]
      RspFindGmLogGmClientCmd_S = 5044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspErrorGmClientCmd_S", Value=5045)]
      RspErrorGmClientCmd_S = 5045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAddRewardGmClientCmd_C", Value=5046)]
      ReqAddRewardGmClientCmd_C = 5046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAddRewardGmClientCmd_S", Value=5047)]
      RspAddRewardGmClientCmd_S = 5047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelRewardGmClientCmd_C", Value=5048)]
      ReqDelRewardGmClientCmd_C = 5048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDelRewardGmClientCmd_S", Value=5049)]
      RspDelRewardGmClientCmd_S = 5049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRewardListGmClientCmd_C", Value=5050)]
      ReqRewardListGmClientCmd_C = 5050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspRewardListGmClientCmd_S", Value=5051)]
      RspRewardListGmClientCmd_S = 5051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRankListClientCmd_C", Value=5052)]
      ReqRankListClientCmd_C = 5052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspPVAIRankListClientCmd_S", Value=5053)]
      RspPVAIRankListClientCmd_S = 5053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspFightRankListClientCmd_S", Value=5054)]
      RspFightRankListClientCmd_S = 5054,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqSTATOperateGmClientCmd_C", Value=5055)]
      ReqSTATOperateGmClientCmd_C = 5055,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspSTATOperateGmClientCmd_S", Value=5056)]
      RspSTATOperateGmClientCmd_S = 5056,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDelPlayerItemGmClientCmd_CS", Value=5057)]
      ReqDelPlayerItemGmClientCmd_CS = 5057,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqPlayerDelItemTodoGmClientCmd_CS", Value=5058)]
      ReqPlayerDelItemTodoGmClientCmd_CS = 5058,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCancelDelItemTodoGmClientCmd_C", Value=5059)]
      ReqCancelDelItemTodoGmClientCmd_C = 5059,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspCancelDelItemTodoGmClientCmd_S", Value=5060)]
      RspCancelDelItemTodoGmClientCmd_S = 5060,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRedirectCsGmClientCmd_C", Value=5061)]
      ReqRedirectCsGmClientCmd_C = 5061,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqConsumeLogGmClientCmd_C", Value=5062)]
      ReqConsumeLogGmClientCmd_C = 5062,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDiamondConsumeGmClientCmd_S", Value=5063)]
      RspDiamondConsumeGmClientCmd_S = 5063,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspItemConsumeGmClientCmd_S", Value=5064)]
      RspItemConsumeGmClientCmd_S = 5064,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqKeyInfoGmClientCmd_C", Value=5070)]
      ReqKeyInfoGmClientCmd_C = 5070,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspKeyInfoGmClientCmd_S", Value=5071)]
      RspKeyInfoGmClientCmd_S = 5071,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqKeyNumGmClientCmd_C", Value=5072)]
      ReqKeyNumGmClientCmd_C = 5072,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspKeyNumGmClientCmd_S", Value=5073)]
      RspKeyNumGmClientCmd_S = 5073,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqAdvFindPlayerGmClientCmd_C", Value=5074)]
      ReqAdvFindPlayerGmClientCmd_C = 5074,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspAdvFindPlayerGmClientCmd_S", Value=5075)]
      RspAdvFindPlayerGmClientCmd_S = 5075,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqProblemGmClientCmd_C", Value=5076)]
      ReqProblemGmClientCmd_C = 5076,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspProblemGmClientCmd_S", Value=5077)]
      RspProblemGmClientCmd_S = 5077,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqProblemListGmClientCmd_C", Value=5078)]
      ReqProblemListGmClientCmd_C = 5078,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspProblemListGmClientCmd_S", Value=5079)]
      RspProblemListGmClientCmd_S = 5079,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqKeepAliveGmClientCmd_CS", Value=5080)]
      ReqKeepAliveGmClientCmd_CS = 5080,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspKeepAliveGmClientCmd_CS", Value=5081)]
      RspKeepAliveGmClientCmd_CS = 5081,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateProblemStateClientCmd_CS", Value=5082)]
      UpdateProblemStateClientCmd_CS = 5082,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueryQuestionnaireClientCmd_C", Value=5083)]
      QueryQuestionnaireClientCmd_C = 5083,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQuestionnaireListClientCmd_S", Value=5084)]
      RspQuestionnaireListClientCmd_S = 5084,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspQuestionnaireClientCmd_S", Value=5086)]
      RspQuestionnaireClientCmd_S = 5086,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqCheckMailAttchCmd_CS", Value=5087)]
      ReqCheckMailAttchCmd_CS = 5087,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqUploadPlayerSqlCmd_C", Value=5101)]
      ReqUploadPlayerSqlCmd_C = 5101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspUploadPlayerSqlCmd_S", Value=5102)]
      RspUploadPlayerSqlCmd_S = 5102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqDownloadPlayerSqlCmd_C", Value=5103)]
      ReqDownloadPlayerSqlCmd_C = 5103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RspDownloadPlayerSqlCmd_S", Value=5104)]
      RspDownloadPlayerSqlCmd_S = 5104
    }
  
}