//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KGame.proto
namespace ProtoCmd
{
    [global::ProtoBuf.ProtoContract(Name=@"CodeVerDef1")]
    public enum CodeVerDef1
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CODEVER_DEF1", Value=0)]
      CODEVER_DEF1 = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CodeVerDef2")]
    public enum CodeVerDef2
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CODEVER_DEF2", Value=34)]
      CODEVER_DEF2 = 34
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneEntryType")]
    public enum SceneEntryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_Invalid", Value=0)]
      SceneEntry_Invalid = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_PlayerCharacter", Value=1)]
      SceneEntry_PlayerCharacter = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_Monster", Value=2)]
      SceneEntry_Monster = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_Npc", Value=3)]
      SceneEntry_Npc = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_VirtualPlayer", Value=10)]
      SceneEntry_VirtualPlayer = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_Character", Value=13)]
      SceneEntry_Character = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntry_MAXV", Value=14)]
      SceneEntry_MAXV = 14
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SceneEntryState")]
    public enum SceneEntryState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Normal", Value=0)]
      SceneEntryState_Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Death", Value=1)]
      SceneEntryState_Death = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Hide", Value=2)]
      SceneEntryState_Hide = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Booth", Value=3)]
      SceneEntryState_Booth = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Ride", Value=4)]
      SceneEntryState_Ride = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Machining", Value=5)]
      SceneEntryState_Machining = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_Destroy", Value=6)]
      SceneEntryState_Destroy = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_InEscort", Value=7)]
      SceneEntryState_InEscort = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_DeathHide", Value=8)]
      SceneEntryState_DeathHide = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneEntryState_MAXV", Value=9)]
      SceneEntryState_MAXV = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DirType")]
    public enum DirType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Up", Value=0)]
      DirType_Up = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_RightUp", Value=1)]
      DirType_RightUp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Right", Value=2)]
      DirType_Right = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_RightDown", Value=3)]
      DirType_RightDown = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Down", Value=4)]
      DirType_Down = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_LeftDown", Value=5)]
      DirType_LeftDown = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Left", Value=6)]
      DirType_Left = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_LeftUp", Value=7)]
      DirType_LeftUp = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Wrong", Value=8)]
      DirType_Wrong = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DirType_Random", Value=9)]
      DirType_Random = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BlockType")]
    public enum BlockType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockNone", Value=0)]
      BlockNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockWalk", Value=1)]
      BlockWalk = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockDynamic", Value=2)]
      BlockDynamic = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockFight", Value=4)]
      BlockFight = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockSell", Value=8)]
      BlockSell = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockSafeAll", Value=16)]
      BlockSafeAll = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockFly", Value=32)]
      BlockFly = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockMagic", Value=64)]
      BlockMagic = 64
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MoveResultType")]
    public enum MoveResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Succ", Value=0)]
      MoveResultType_Succ = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_Unknown", Value=1)]
      MoveResultType_Fail_Unknown = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_StateWrong", Value=2)]
      MoveResultType_Fail_StateWrong = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_Block", Value=3)]
      MoveResultType_Fail_Block = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_TooFar", Value=4)]
      MoveResultType_Fail_TooFar = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_TooFast", Value=5)]
      MoveResultType_Fail_TooFast = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_Fail_InMachine", Value=6)]
      MoveResultType_Fail_InMachine = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveResultType_MaxV", Value=7)]
      MoveResultType_MaxV = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlatDefine")]
    public enum PlatDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_test", Value=0)]
      PlatDefine_test = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_weixin", Value=1)]
      PlatDefine_weixin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_qq", Value=2)]
      PlatDefine_qq = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_oppo", Value=3)]
      PlatDefine_oppo = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_vivo", Value=4)]
      PlatDefine_vivo = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_huawei", Value=5)]
      PlatDefine_huawei = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_360", Value=6)]
      PlatDefine_360 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_xiaomi", Value=7)]
      PlatDefine_xiaomi = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_toutiao", Value=8)]
      PlatDefine_toutiao = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_weibo", Value=9)]
      PlatDefine_weibo = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_baidu", Value=10)]
      PlatDefine_baidu = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_uc", Value=11)]
      PlatDefine_uc = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_iqiyi", Value=12)]
      PlatDefine_iqiyi = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_youku", Value=13)]
      PlatDefine_youku = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_kuaishou", Value=14)]
      PlatDefine_kuaishou = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_163", Value=15)]
      PlatDefine_163 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_mm", Value=16)]
      PlatDefine_mm = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_sogou", Value=17)]
      PlatDefine_sogou = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_xinpai", Value=18)]
      PlatDefine_xinpai = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_37", Value=19)]
      PlatDefine_37 = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_mianshangdian", Value=20)]
      PlatDefine_mianshangdian = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_ourpalm", Value=21)]
      PlatDefine_ourpalm = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_youzu", Value=22)]
      PlatDefine_youzu = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_king", Value=23)]
      PlatDefine_king = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_tianshen", Value=24)]
      PlatDefine_tianshen = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_yingxiong", Value=25)]
      PlatDefine_yingxiong = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_kugou", Value=26)]
      PlatDefine_kugou = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_4399", Value=27)]
      PlatDefine_4399 = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_lenovo", Value=28)]
      PlatDefine_lenovo = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_kupai", Value=29)]
      PlatDefine_kupai = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_jinli", Value=30)]
      PlatDefine_jinli = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_meizu", Value=31)]
      PlatDefine_meizu = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_leshi", Value=32)]
      PlatDefine_leshi = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_quick", Value=33)]
      PlatDefine_quick = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_shunwang", Value=34)]
      PlatDefine_shunwang = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_wandoujia", Value=35)]
      PlatDefine_wandoujia = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_guopan", Value=36)]
      PlatDefine_guopan = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_mumayi", Value=37)]
      PlatDefine_mumayi = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_anzhi", Value=38)]
      PlatDefine_anzhi = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_youmi", Value=39)]
      PlatDefine_youmi = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_dangle", Value=40)]
      PlatDefine_dangle = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_yingyonghui", Value=41)]
      PlatDefine_yingyonghui = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlatDefine_pengyouwan", Value=42)]
      PlatDefine_pengyouwan = 42
    }
  
}