//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LinkCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRoleLinkClientCmd")]
  public partial class ReqRoleLinkClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqRoleLinkClientCmd() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkData")]
  public partial class LinkData : global::ProtoBuf.IExtensible
  {
    public LinkData() {}
    
    private uint _link_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"link_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_id
    {
      get { return _link_id; }
      set { _link_id = value; }
    }
    private uint _link_level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"link_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_level
    {
      get { return _link_level; }
      set { _link_level = value; }
    }
    private uint _link_exp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"link_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_exp
    {
      get { return _link_exp; }
      set { _link_exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspRoleLinkClientCmd")]
  public partial class RspRoleLinkClientCmd : global::ProtoBuf.IExtensible
  {
    public RspRoleLinkClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.LinkData> _link_list = new global::System.Collections.Generic.List<ProtoCmd.LinkData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"link_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.LinkData> link_list
    {
      get { return _link_list; }
    }
  
    private uint _lastreferlink_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastreferlink_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lastreferlink_id
    {
      get { return _lastreferlink_id; }
      set { _lastreferlink_id = value; }
    }
    private uint _result = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAddRoleLinkClientCmd")]
  public partial class ReqAddRoleLinkClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqAddRoleLinkClientCmd() {}
    
    private uint _role_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private uint _role_id2 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"role_id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint role_id2
    {
      get { return _role_id2; }
      set { _role_id2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAddRoleLinkExpClientCmd")]
  public partial class ReqAddRoleLinkExpClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqAddRoleLinkExpClientCmd() {}
    
    private uint _link_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"link_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_id
    {
      get { return _link_id; }
      set { _link_id = value; }
    }
    private uint _link_exp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"link_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_exp
    {
      get { return _link_exp; }
      set { _link_exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspRoleLinkUpGradeClientCmd")]
  public partial class RspRoleLinkUpGradeClientCmd : global::ProtoBuf.IExtensible
  {
    public RspRoleLinkUpGradeClientCmd() {}
    
    private uint _link_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"link_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_id
    {
      get { return _link_id; }
      set { _link_id = value; }
    }
    private uint _link_level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"link_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint link_level
    {
      get { return _link_level; }
      set { _link_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExchangePresentsClientCmd")]
  public partial class ExchangePresentsClientCmd : global::ProtoBuf.IExtensible
  {
    public ExchangePresentsClientCmd() {}
    
    private ProtoCmd.LinkData _link_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"link_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.LinkData link_data
    {
      get { return _link_data; }
      set { _link_data = value; }
    }
    private uint _item_num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_num
    {
      get { return _item_num; }
      set { _item_num = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSaveLastReferLinkClientCmd")]
  public partial class ReqSaveLastReferLinkClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqSaveLastReferLinkClientCmd() {}
    
    private uint _lastreferlink_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lastreferlink_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lastreferlink_id
    {
      get { return _lastreferlink_id; }
      set { _lastreferlink_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}