//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: map_screen_define.proto
// Note: requires additional types generated from: SkillCommand.proto
// Note: requires additional types generated from: FbDefine.proto
// Note: requires additional types generated from: ItemDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEntryBase")]
  public partial class MapEntryBase : global::ProtoBuf.IExtensible
  {
    public MapEntryBase() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _pos_x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapPlayer")]
  public partial class MapPlayer : global::ProtoBuf.IExtensible
  {
    public MapPlayer() {}
    
    private ProtoCmd.MapEntryBase _Base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapEntryBase Base
    {
      get { return _Base; }
      set { _Base = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _relation = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"relation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint relation
    {
      get { return _relation; }
      set { _relation = value; }
    }
    private uint _vip_level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }
    private byte[] _guild_name = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private uint _guild_post = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"guild_post", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guild_post
    {
      get { return _guild_post; }
      set { _guild_post = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNpc")]
  public partial class MapNpc : global::ProtoBuf.IExtensible
  {
    public MapNpc() {}
    
    private ProtoCmd.MapEntryBase _Base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapEntryBase Base
    {
      get { return _Base; }
      set { _Base = value; }
    }
    private uint _npc_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _atb = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"atb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> atb
    {
      get { return _atb; }
    }
  
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _delay = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"delay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint delay
    {
      get { return _delay; }
      set { _delay = value; }
    }
    private uint _wave_id = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"wave_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wave_id
    {
      get { return _wave_id; }
      set { _wave_id = value; }
    }
    private float _rot_y = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private uint _master_id = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"master_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_id
    {
      get { return _master_id; }
      set { _master_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.SkillInfo> _skill = new global::System.Collections.Generic.List<ProtoCmd.SkillInfo>();
    [global::ProtoBuf.ProtoMember(10, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.SkillInfo> skill
    {
      get { return _skill; }
    }
  
    private uint _rand_index = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rand_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rand_index
    {
      get { return _rand_index; }
      set { _rand_index = value; }
    }
    private uint _skill_id = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapMonster")]
  public partial class MapMonster : global::ProtoBuf.IExtensible
  {
    public MapMonster() {}
    
    private ProtoCmd.MapNpc _npcdata = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"npcdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapNpc npcdata
    {
      get { return _npcdata; }
      set { _npcdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapLost")]
  public partial class MapLost : global::ProtoBuf.IExtensible
  {
    public MapLost() {}
    
    private ProtoCmd.MapEntryBase _Base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapEntryBase Base
    {
      get { return _Base; }
      set { _Base = value; }
    }
    private uint _item_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private uint _owner_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private uint _owner_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"owner_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint owner_type
    {
      get { return _owner_type; }
      set { _owner_type = value; }
    }
    private uint _attch_money = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"attch_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attch_money
    {
      get { return _attch_money; }
      set { _attch_money = value; }
    }
    private uint _item_quality = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"item_quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint item_quality
    {
      get { return _item_quality; }
      set { _item_quality = value; }
    }
    private uint _attch_money_type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"attch_money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attch_money_type
    {
      get { return _attch_money_type; }
      set { _attch_money_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapPlayerBaseData")]
  public partial class MapPlayerBaseData : global::ProtoBuf.IExtensible
  {
    public MapPlayerBaseData() {}
    
    private uint _accid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint accid
    {
      get { return _accid; }
      set { _accid = value; }
    }
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _headpic = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headpic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headpic
    {
      get { return _headpic; }
      set { _headpic = value; }
    }
    private uint _headindex = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"headindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headindex
    {
      get { return _headindex; }
      set { _headindex = value; }
    }
    private uint _headback = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"headback", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint headback
    {
      get { return _headback; }
      set { _headback = value; }
    }
    private uint _psex = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"psex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint psex
    {
      get { return _psex; }
      set { _psex = value; }
    }
    private uint _plevel = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"plevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint plevel
    {
      get { return _plevel; }
      set { _plevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapCharacterBaseData")]
  public partial class MapCharacterBaseData : global::ProtoBuf.IExtensible
  {
    public MapCharacterBaseData() {}
    
    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private string _charname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charname
    {
      get { return _charname; }
      set { _charname = value; }
    }
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _roleid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roleid
    {
      get { return _roleid; }
      set { _roleid = value; }
    }
    private uint _sceneid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sceneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sceneid
    {
      get { return _sceneid; }
      set { _sceneid = value; }
    }
    private float _pos_x = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _atb = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"atb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> atb
    {
      get { return _atb; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _ext = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ext
    {
      get { return _ext; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _equipindex = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> equipindex
    {
      get { return _equipindex; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MainMapPlayer")]
  public partial class MainMapPlayer : global::ProtoBuf.IExtensible
  {
    public MainMapPlayer() {}
    
    private ProtoCmd.MapPlayerBaseData _player_base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapPlayerBaseData player_base
    {
      get { return _player_base; }
      set { _player_base = value; }
    }
    private ProtoCmd.MapCharacterBaseData _character_base = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"character_base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapCharacterBaseData character_base
    {
      get { return _character_base; }
      set { _character_base = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}