//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: map_screen_command.proto
// Note: requires additional types generated from: map_screen_define.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatchRemovePlayerMapScreenClientCmd")]
  public partial class BatchRemovePlayerMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public BatchRemovePlayerMapScreenClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ids
    {
      get { return _ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemovePlayerMapScreenClientCmd")]
  public partial class RemovePlayerMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public RemovePlayerMapScreenClientCmd() {}
    
    private uint _pid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddPlayerMapScreenClientCmd")]
  public partial class AddPlayerMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public AddPlayerMapScreenClientCmd() {}
    
    private ProtoCmd.MapPlayer _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapPlayer data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatchAddPlayerMapScreenClientCmd")]
  public partial class BatchAddPlayerMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public BatchAddPlayerMapScreenClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.MapPlayer> _data = new global::System.Collections.Generic.List<ProtoCmd.MapPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.MapPlayer> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspAddPlayerCmd")]
  public partial class RspAddPlayerCmd : global::ProtoBuf.IExtensible
  {
    public RspAddPlayerCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.MainMapPlayer> _data = new global::System.Collections.Generic.List<ProtoCmd.MainMapPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.MainMapPlayer> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspRemovePlayerCmd")]
  public partial class RspRemovePlayerCmd : global::ProtoBuf.IExtensible
  {
    public RspRemovePlayerCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ids
    {
      get { return _ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMapMapScreenClientCmd")]
  public partial class AddMapMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public AddMapMapScreenClientCmd() {}
    
    private uint _scene_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"scene_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint scene_id
    {
      get { return _scene_id; }
      set { _scene_id = value; }
    }
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _fresh = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fresh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool fresh
    {
      get { return _fresh; }
      set { _fresh = value; }
    }
    private bool _is_login = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_login
    {
      get { return _is_login; }
      set { _is_login = value; }
    }
    private uint _level_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level_id
    {
      get { return _level_id; }
      set { _level_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddNpcMapScreenClientCmd")]
  public partial class AddNpcMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public AddNpcMapScreenClientCmd() {}
    
    private ProtoCmd.MapMonster _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.MapMonster data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveNpcMapScreenClientCmd")]
  public partial class RemoveNpcMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public RemoveNpcMapScreenClientCmd() {}
    
    private uint _npc_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"npc_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint npc_id
    {
      get { return _npc_id; }
      set { _npc_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatchRemoveNpcMapScreenClientCmd")]
  public partial class BatchRemoveNpcMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public BatchRemoveNpcMapScreenClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ids
    {
      get { return _ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatchAddNpcMapScreenClientCmd")]
  public partial class BatchAddNpcMapScreenClientCmd : global::ProtoBuf.IExtensible
  {
    public BatchAddNpcMapScreenClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.MapMonster> _data = new global::System.Collections.Generic.List<ProtoCmd.MapMonster>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.MapMonster> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterMMOMainCityClientCmd")]
  public partial class ReqEnterMMOMainCityClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqEnterMMOMainCityClientCmd() {}
    
    private uint _characterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint characterId
    {
      get { return _characterId; }
      set { _characterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}