//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerDataCommand.proto
// Note: requires additional types generated from: PlayerDataDefine.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshMoneyDataClientCmd")]
  public partial class RefreshMoneyDataClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshMoneyDataClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _money = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> money
    {
      get { return _money; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoneyChangeClientCmd")]
  public partial class MoneyChangeClientCmd : global::ProtoBuf.IExtensible
  {
    public MoneyChangeClientCmd() {}
    
    private int _money_type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private long _money_change = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money_change
    {
      get { return _money_change; }
      set { _money_change = value; }
    }
    private ulong _money_total = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money_total", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong money_total
    {
      get { return _money_total; }
      set { _money_total = value; }
    }
    private uint _action = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayerMainDataClientCmd")]
  public partial class UpdatePlayerMainDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdatePlayerMainDataClientCmd() {}
    
    private ProtoCmd.PlayerMainData _main_player_data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"main_player_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.PlayerMainData main_player_data
    {
      get { return _main_player_data; }
      set { _main_player_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePlayerFriendlyClientCmd")]
  public partial class UpdatePlayerFriendlyClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdatePlayerFriendlyClientCmd() {}
    
    private uint _friendly = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"friendly", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendly
    {
      get { return _friendly; }
      set { _friendly = value; }
    }
    private uint _friendly_today = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friendly_today", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendly_today
    {
      get { return _friendly_today; }
      set { _friendly_today = value; }
    }
    private uint _friendly_limit = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"friendly_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendly_limit
    {
      get { return _friendly_limit; }
      set { _friendly_limit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateHpClientCmd")]
  public partial class UpdateHpClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateHpClientCmd() {}
    
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePhysicalClientCmd")]
  public partial class UpdatePhysicalClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdatePhysicalClientCmd() {}
    
    private uint _physical = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"physical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint physical
    {
      get { return _physical; }
      set { _physical = value; }
    }
    private uint _resume_physical = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resume_physical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resume_physical
    {
      get { return _resume_physical; }
      set { _resume_physical = value; }
    }
    private bool _is_count_down = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"is_count_down", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_count_down
    {
      get { return _is_count_down; }
      set { _is_count_down = value; }
    }
    private uint _count_down = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"count_down", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count_down
    {
      get { return _count_down; }
      set { _count_down = value; }
    }
    private uint _left_buy_count = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"left_buy_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint left_buy_count
    {
      get { return _left_buy_count; }
      set { _left_buy_count = value; }
    }
    private uint _max_recv_phy = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"max_recv_phy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_recv_phy
    {
      get { return _max_recv_phy; }
      set { _max_recv_phy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPhyscialClientCmd")]
  public partial class BuyPhyscialClientCmd : global::ProtoBuf.IExtensible
  {
    public BuyPhyscialClientCmd() {}
    
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UsePhyscialItemClientCmd")]
  public partial class UsePhyscialItemClientCmd : global::ProtoBuf.IExtensible
  {
    public UsePhyscialItemClientCmd() {}
    
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetPhyscialPowerClientCmd")]
  public partial class ReqGetPhyscialPowerClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqGetPhyscialPowerClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateLevelExpDataClientCmd")]
  public partial class UpdateLevelExpDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateLevelExpDataClientCmd() {}
    
    private uint _char_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private bool _is_level_up = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_level_up", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_level_up
    {
      get { return _is_level_up; }
      set { _is_level_up = value; }
    }
    private uint _add_exp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"add_exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint add_exp
    {
      get { return _add_exp; }
      set { _add_exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateSysSetDataClientCmd")]
  public partial class UpdateSysSetDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateSysSetDataClientCmd() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateClientConfigDataClientCmd")]
  public partial class UpdateClientConfigDataClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateClientConfigDataClientCmd() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddExpDataTipsClientCmd")]
  public partial class AddExpDataTipsClientCmd : global::ProtoBuf.IExtensible
  {
    public AddExpDataTipsClientCmd() {}
    
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddMoneyDataTipsClientCmd")]
  public partial class AddMoneyDataTipsClientCmd : global::ProtoBuf.IExtensible
  {
    public AddMoneyDataTipsClientCmd() {}
    
    private uint _money_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private uint _money_num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_num
    {
      get { return _money_num; }
      set { _money_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncLogicConfigParamClientCmd")]
  public partial class SyncLogicConfigParamClientCmd : global::ProtoBuf.IExtensible
  {
    public SyncLogicConfigParamClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _data = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestRelivePlayerDeathReliveClientCmd")]
  public partial class RequestRelivePlayerDeathReliveClientCmd : global::ProtoBuf.IExtensible
  {
    public RequestRelivePlayerDeathReliveClientCmd() {}
    
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RelivePlayerDeathReliveClientCmd")]
  public partial class RelivePlayerDeathReliveClientCmd : global::ProtoBuf.IExtensible
  {
    public RelivePlayerDeathReliveClientCmd() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private uint _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _buffs = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> buffs
    {
      get { return _buffs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RelivePlayerFailClientCmd")]
  public partial class RelivePlayerFailClientCmd : global::ProtoBuf.IExtensible
  {
    public RelivePlayerFailClientCmd() {}
    
    private uint _ret = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestReliveClientCmd")]
  public partial class RequestReliveClientCmd : global::ProtoBuf.IExtensible
  {
    public RequestReliveClientCmd() {}
    
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateMasterCharIdCmd")]
  public partial class UpdateMasterCharIdCmd : global::ProtoBuf.IExtensible
  {
    public UpdateMasterCharIdCmd() {}
    
    private uint _player_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private uint _master_charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"master_charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint master_charid
    {
      get { return _master_charid; }
      set { _master_charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerFlagData")]
  public partial class PlayerFlagData : global::ProtoBuf.IExtensible
  {
    public PlayerFlagData() {}
    
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendPlayerFlagCmd")]
  public partial class SendPlayerFlagCmd : global::ProtoBuf.IExtensible
  {
    public SendPlayerFlagCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.PlayerFlagData> _data = new global::System.Collections.Generic.List<ProtoCmd.PlayerFlagData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.PlayerFlagData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshSpaceDanMuListClientCmd")]
  public partial class RefreshSpaceDanMuListClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshSpaceDanMuListClientCmd() {}
    
    private uint _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<byte[]> _danmu = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(2, Name=@"danmu", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> danmu
    {
      get { return _danmu; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetSpaceMoodClientCmd")]
  public partial class SetSpaceMoodClientCmd : global::ProtoBuf.IExtensible
  {
    public SetSpaceMoodClientCmd() {}
    
    private byte[] _mood;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mood", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] mood
    {
      get { return _mood; }
      set { _mood = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGuideSystemClientCmd")]
  public partial class ReqGuideSystemClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqGuideSystemClientCmd() {}
    
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _step = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private uint _status = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspGuideSystemClientCmd")]
  public partial class RspGuideSystemClientCmd : global::ProtoBuf.IExtensible
  {
    public RspGuideSystemClientCmd() {}
    
    private uint _rst = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStoryAwardClientCmd")]
  public partial class ReqStoryAwardClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqStoryAwardClientCmd() {}
    
    private uint _story_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"story_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint story_id
    {
      get { return _story_id; }
      set { _story_id = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshHeadInfoCmd")]
  public partial class RefreshHeadInfoCmd : global::ProtoBuf.IExtensible
  {
    public RefreshHeadInfoCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _head_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"head_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> head_id
    {
      get { return _head_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddHeadInfoCmd")]
  public partial class AddHeadInfoCmd : global::ProtoBuf.IExtensible
  {
    public AddHeadInfoCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _head_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"head_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> head_id
    {
      get { return _head_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapHeadIndexClientCmd")]
  public partial class SwapHeadIndexClientCmd : global::ProtoBuf.IExtensible
  {
    public SwapHeadIndexClientCmd() {}
    
    private uint _head_index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"head_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head_index
    {
      get { return _head_index; }
      set { _head_index = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapHeadBackClientCmd")]
  public partial class SwapHeadBackClientCmd : global::ProtoBuf.IExtensible
  {
    public SwapHeadBackClientCmd() {}
    
    private uint _head_back = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"head_back", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head_back
    {
      get { return _head_back; }
      set { _head_back = value; }
    }
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqQuestionnaireRewardClientCmd")]
  public partial class ReqQuestionnaireRewardClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqQuestionnaireRewardClientCmd() {}
    
    private uint _playerid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private string _str_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"str_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string str_id
    {
      get { return _str_id; }
      set { _str_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspQuestionnaireClientCmd")]
  public partial class RspQuestionnaireClientCmd : global::ProtoBuf.IExtensible
  {
    public RspQuestionnaireClientCmd() {}
    
    private uint _quest_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"quest_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quest_id
    {
      get { return _quest_id; }
      set { _quest_id = value; }
    }
    private string _quest_url = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"quest_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string quest_url
    {
      get { return _quest_url; }
      set { _quest_url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspFirstGuildClientCmd")]
  public partial class RspFirstGuildClientCmd : global::ProtoBuf.IExtensible
  {
    public RspFirstGuildClientCmd() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _step = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieStep")]
  public partial class NewBieStep : global::ProtoBuf.IExtensible
  {
    public NewBieStep() {}
    
    private uint _BId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BId
    {
      get { return _BId; }
      set { _BId = value; }
    }
    private uint _SId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SId
    {
      get { return _SId; }
      set { _SId = value; }
    }
    private ProtoCmd.NewBieStepStatus _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoCmd.NewBieStepStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspNewBieStepClientCmd")]
  public partial class RspNewBieStepClientCmd : global::ProtoBuf.IExtensible
  {
    public RspNewBieStepClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.NewBieStep> _newBieStep = new global::System.Collections.Generic.List<ProtoCmd.NewBieStep>();
    [global::ProtoBuf.ProtoMember(1, Name=@"newBieStep", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.NewBieStep> newBieStep
    {
      get { return _newBieStep; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartNewBieStepClientCmd")]
  public partial class ReqStartNewBieStepClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqStartNewBieStepClientCmd() {}
    
    private uint _BId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BId
    {
      get { return _BId; }
      set { _BId = value; }
    }
    private uint _SId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SId
    {
      get { return _SId; }
      set { _SId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqFinishNewBieStepClientCmd")]
  public partial class ReqFinishNewBieStepClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqFinishNewBieStepClientCmd() {}
    
    private uint _BId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BId
    {
      get { return _BId; }
      set { _BId = value; }
    }
    private uint _SId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SId
    {
      get { return _SId; }
      set { _SId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnergyValue")]
  public partial class EnergyValue : global::ProtoBuf.IExtensible
  {
    public EnergyValue() {}
    
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshEnergyClientCmd")]
  public partial class RefreshEnergyClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshEnergyClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.EnergyValue> _energy = new global::System.Collections.Generic.List<ProtoCmd.EnergyValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.EnergyValue> energy
    {
      get { return _energy; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeMainYardMapIdClientCmd")]
  public partial class ReqChangeMainYardMapIdClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqChangeMainYardMapIdClientCmd() {}
    
    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckAllMainYardMapIdClientCmd")]
  public partial class CheckAllMainYardMapIdClientCmd : global::ProtoBuf.IExtensible
  {
    public CheckAllMainYardMapIdClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<uint> _mainyardskinid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mainyardskinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mainyardskinid
    {
      get { return _mainyardskinid; }
    }
  
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnLockMainYardMapIdClientCmd")]
  public partial class UnLockMainYardMapIdClientCmd : global::ProtoBuf.IExtensible
  {
    public UnLockMainYardMapIdClientCmd() {}
    
    private uint _mainyardskinid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mainyardskinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mainyardskinid
    {
      get { return _mainyardskinid; }
      set { _mainyardskinid = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DebrisAwakenCardClientCmd")]
  public partial class DebrisAwakenCardClientCmd : global::ProtoBuf.IExtensible
  {
    public DebrisAwakenCardClientCmd() {}
    
    private uint _cardid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cardid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardid
    {
      get { return _cardid; }
      set { _cardid = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateActivityClientCmd")]
  public partial class UpdateActivityClientCmd : global::ProtoBuf.IExtensible
  {
    public UpdateActivityClientCmd() {}
    
    private uint _daily_activity = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"daily_activity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint daily_activity
    {
      get { return _daily_activity; }
      set { _daily_activity = value; }
    }
    private uint _weekly_activity = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"weekly_activity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weekly_activity
    {
      get { return _weekly_activity; }
      set { _weekly_activity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqActiveRewardClientCmd")]
  public partial class ReqActiveRewardClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqActiveRewardClientCmd() {}
    
    private uint _reward_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reward_id
    {
      get { return _reward_id; }
      set { _reward_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RewardStatus")]
  public partial class RewardStatus : global::ProtoBuf.IExtensible
  {
    public RewardStatus() {}
    
    private uint _reward_key = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reward_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reward_key
    {
      get { return _reward_key; }
      set { _reward_key = value; }
    }
    private uint _reward_status = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reward_status
    {
      get { return _reward_status; }
      set { _reward_status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncActivityRewardClientCmd")]
  public partial class SyncActivityRewardClientCmd : global::ProtoBuf.IExtensible
  {
    public SyncActivityRewardClientCmd() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.RewardStatus> _data = new global::System.Collections.Generic.List<ProtoCmd.RewardStatus>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.RewardStatus> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BindAccountClientCmd")]
  public partial class BindAccountClientCmd : global::ProtoBuf.IExtensible
  {
    public BindAccountClientCmd() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuideLinearStep")]
    public enum GuideLinearStep
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gls_None", Value=0)]
      Gls_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gls_ShowRoleInfo", Value=1)]
      Gls_ShowRoleInfo = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuideNolinearStep")]
    public enum GuideNolinearStep
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_None", Value=0)]
      Gns_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuidePlot", Value=1)]
      Gns_GuidePlot = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideUnlockFightDegree", Value=2)]
      Gns_GuideUnlockFightDegree = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideFriarUpgrade", Value=3)]
      Gns_GuideFriarUpgrade = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideAutoFight", Value=4)]
      Gns_GuideAutoFight = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideTask", Value=5)]
      Gns_GuideTask = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideTravelSecondTeam", Value=6)]
      Gns_GuideTravelSecondTeam = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gns_GuideCompanionsTravel", Value=7)]
      Gns_GuideCompanionsTravel = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NewBieStepStatus")]
    public enum NewBieStepStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eStart", Value=1)]
      eStart = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFinish", Value=2)]
      eFinish = 2
    }
  
}