//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StatCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map_si32_item")]
  public partial class Map_si32_item : global::ProtoBuf.IExtensible
  {
    public Map_si32_item() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"List_map_si32")]
  public partial class List_map_si32 : global::ProtoBuf.IExtensible
  {
    public List_map_si32() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.Map_si32_item> _item = new global::System.Collections.Generic.List<ProtoCmd.Map_si32_item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.Map_si32_item> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"List_map_ss")]
  public partial class List_map_ss : global::ProtoBuf.IExtensible
  {
    public List_map_ss() {}
    
    private readonly global::System.Collections.Generic.List<ProtoCmd.Map_ss_item> _item = new global::System.Collections.Generic.List<ProtoCmd.Map_ss_item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.Map_ss_item> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Map_ss_item")]
  public partial class Map_ss_item : global::ProtoBuf.IExtensible
  {
    public Map_ss_item() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"List_i32_item")]
  public partial class List_i32_item : global::ProtoBuf.IExtensible
  {
    public List_i32_item() {}
    
    private int _i32;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"i32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int i32
    {
      get { return _i32; }
      set { _i32 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgInfo")]
  public partial class MsgInfo : global::ProtoBuf.IExtensible
  {
    public MsgInfo() {}
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _u32 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"u32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint u32
    {
      get { return _u32; }
      set { _u32 = value; }
    }
    private int _i32 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"i32", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int i32
    {
      get { return _i32; }
      set { _i32 = value; }
    }
    private ulong _u64 = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"u64", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong u64
    {
      get { return _u64; }
      set { _u64 = value; }
    }
    private byte[] _s = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] s
    {
      get { return _s; }
      set { _s = value; }
    }
    private float _f = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float f
    {
      get { return _f; }
      set { _f = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.List_i32_item> _list_i32 = new global::System.Collections.Generic.List<ProtoCmd.List_i32_item>();
    [global::ProtoBuf.ProtoMember(8, Name=@"list_i32", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.List_i32_item> list_i32
    {
      get { return _list_i32; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.Map_si32_item> _map_si32 = new global::System.Collections.Generic.List<ProtoCmd.Map_si32_item>();
    [global::ProtoBuf.ProtoMember(9, Name=@"map_si32", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.Map_si32_item> map_si32
    {
      get { return _map_si32; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.Map_ss_item> _map_ss = new global::System.Collections.Generic.List<ProtoCmd.Map_ss_item>();
    [global::ProtoBuf.ProtoMember(10, Name=@"map_ss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.Map_ss_item> map_ss
    {
      get { return _map_ss; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.List_map_si32> _list_map_si32 = new global::System.Collections.Generic.List<ProtoCmd.List_map_si32>();
    [global::ProtoBuf.ProtoMember(11, Name=@"list_map_si32", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.List_map_si32> list_map_si32
    {
      get { return _list_map_si32; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoCmd.List_map_ss> _list_map_ss = new global::System.Collections.Generic.List<ProtoCmd.List_map_ss>();
    [global::ProtoBuf.ProtoMember(12, Name=@"list_map_ss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.List_map_ss> list_map_ss
    {
      get { return _list_map_ss; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStatLogReq")]
  public partial class AddStatLogReq : global::ProtoBuf.IExtensible
  {
    public AddStatLogReq() {}
    
    private uint _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private uint _statid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"statid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint statid
    {
      get { return _statid; }
      set { _statid = value; }
    }
    private byte[] _statname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"statname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] statname
    {
      get { return _statname; }
      set { _statname = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.MsgInfo> _infos = new global::System.Collections.Generic.List<ProtoCmd.MsgInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.MsgInfo> infos
    {
      get { return _infos; }
    }
  
    private byte[] _playerid = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStatLogReq_json")]
  public partial class AddStatLogReq_json : global::ProtoBuf.IExtensible
  {
    public AddStatLogReq_json() {}
    
    private uint _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private byte[] _statname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"statname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] statname
    {
      get { return _statname; }
      set { _statname = value; }
    }
    private byte[] _log;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] log
    {
      get { return _log; }
      set { _log = value; }
    }
    private byte[] _playerid = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}