//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StoreCommand.proto
// Note: requires additional types generated from: ItemCommand.proto
namespace ProtoCmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodsUnit")]
  public partial class GoodsUnit : global::ProtoBuf.IExtensible
  {
    public GoodsUnit() {}
    
    private uint _goods_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint goods_id
    {
      get { return _goods_id; }
      set { _goods_id = value; }
    }
    private uint _goods_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goods_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint goods_type
    {
      get { return _goods_type; }
      set { _goods_type = value; }
    }
    private uint _give_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"give_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint give_id
    {
      get { return _give_id; }
      set { _give_id = value; }
    }
    private uint _give_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"give_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint give_num
    {
      get { return _give_num; }
      set { _give_num = value; }
    }
    private bool _b_coin1 = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"b_coin1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool b_coin1
    {
      get { return _b_coin1; }
      set { _b_coin1 = value; }
    }
    private uint _coin1_price = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"coin1_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint coin1_price
    {
      get { return _coin1_price; }
      set { _coin1_price = value; }
    }
    private bool _b_coin2 = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"b_coin2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool b_coin2
    {
      get { return _b_coin2; }
      set { _b_coin2 = value; }
    }
    private uint _coin2_price = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"coin2_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint coin2_price
    {
      get { return _coin2_price; }
      set { _coin2_price = value; }
    }
    private ulong _offsell_date = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"offsell_date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong offsell_date
    {
      get { return _offsell_date; }
      set { _offsell_date = value; }
    }
    private uint _all_supply = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"all_supply", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_supply
    {
      get { return _all_supply; }
      set { _all_supply = value; }
    }
    private uint _limit_type = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"limit_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint limit_type
    {
      get { return _limit_type; }
      set { _limit_type = value; }
    }
    private uint _limit_num = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"limit_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint limit_num
    {
      get { return _limit_num; }
      set { _limit_num = value; }
    }
    private uint _left_num = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"left_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint left_num
    {
      get { return _left_num; }
      set { _left_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAllStoreGoodsClientCmd")]
  public partial class ReqAllStoreGoodsClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqAllStoreGoodsClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendAllStoreGoodsClientCmd")]
  public partial class SendAllStoreGoodsClientCmd : global::ProtoBuf.IExtensible
  {
    public SendAllStoreGoodsClientCmd() {}
    
    private uint _finish_time = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"finish_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint finish_time
    {
      get { return _finish_time; }
      set { _finish_time = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoCmd.GoodsUnit> _goods = new global::System.Collections.Generic.List<ProtoCmd.GoodsUnit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoCmd.GoodsUnit> goods
    {
      get { return _goods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshStoreGoodsClientCmd")]
  public partial class RefreshStoreGoodsClientCmd : global::ProtoBuf.IExtensible
  {
    public RefreshStoreGoodsClientCmd() {}
    
    private ProtoCmd.GoodsUnit _goods = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoCmd.GoodsUnit goods
    {
      get { return _goods; }
      set { _goods = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyGoodsClientCmd")]
  public partial class ReqBuyGoodsClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqBuyGoodsClientCmd() {}
    
    private uint _goods_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"goods_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint goods_id
    {
      get { return _goods_id; }
      set { _goods_id = value; }
    }
    private uint _goods_num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goods_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint goods_num
    {
      get { return _goods_num; }
      set { _goods_num = value; }
    }
    private uint _coin_type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coin_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint coin_type
    {
      get { return _coin_type; }
      set { _coin_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBuyGoodsClientCmd")]
  public partial class RspBuyGoodsClientCmd : global::ProtoBuf.IExtensible
  {
    public RspBuyGoodsClientCmd() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _rst = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyMonthCardClientCmd")]
  public partial class ReqBuyMonthCardClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqBuyMonthCardClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBuyMonthCardClientCmd")]
  public partial class RspBuyMonthCardClientCmd : global::ProtoBuf.IExtensible
  {
    public RspBuyMonthCardClientCmd() {}
    
    private uint _finish_time = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"finish_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint finish_time
    {
      get { return _finish_time; }
      set { _finish_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyBindDiamondClientCmd")]
  public partial class ReqBuyBindDiamondClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqBuyBindDiamondClientCmd() {}
    
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMonthCardAwardClientCmd")]
  public partial class ReqMonthCardAwardClientCmd : global::ProtoBuf.IExtensible
  {
    public ReqMonthCardAwardClientCmd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspMonthCardAwardClientCmd")]
  public partial class RspMonthCardAwardClientCmd : global::ProtoBuf.IExtensible
  {
    public RspMonthCardAwardClientCmd() {}
    
    private bool _rst = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspRechargeClientCmd")]
  public partial class RspRechargeClientCmd : global::ProtoBuf.IExtensible
  {
    public RspRechargeClientCmd() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}